### ISSUE TITLE
Compile.sh?

### ISSUE THREAD

**Issue by zer00ne** [ableplayer/ableplayer#100]
I'd like to rename and relocate certain directories and files.  In the README.md it says:

"If you make changes to this or any other JavaScript script files, the player will need to be recompiled before your changes will take effect. To do so, run the shell script compile.sh."

I googled shell script compile.sh and only found documentation on specific programs and OSs, nothing much in a general way of explaining how, what where, and why.  As it pertains to Able Player, how would I go about running the shell script compile.sh?  I am one of the many people who only use a PC with Windows 8.  Do I need to use Python?  Would I require a Linux machine?

BTW, thank you for this excellent player, if my boss wasn't so determined to us JW Player, I'd drop it in a heartbeat and use Able Player exclusively.

**Comment by terrill** [comment]
On Unix/Linux, including the Mac OS X command prompt, we just type "sh compile.sh". Unfortunately Windows doesn't support .sh files natively. You would need to install a third party tool like Cygwin to run the .sh file: 
http://superuser.com/questions/120045/how-to-execute-sh-file-on-windows

**Comment by zer00ne** [comment]
Thank you, sir.
