### ISSUE TITLE
Does not work outside of a subdirectory

### ISSUE THREAD

**Issue by afemath** [ableplayer/ableplayer#107]
This player does not load unless the html file that is calling it is in a single subdirectory of the ableplayer folder.

*For example:*

**These work:**
```
ableplayer
    |___tests
        |___*index.html*
    |___whatever
        |___*index.html*
```
**These do not work**
```
ableplayer
    |___*index.html*
    |___tests
        |___whatever
            |___*index.html*
```

I used one of your test files to test this with no alterations to the file except for the relative paths to the assets. I used web developer tools to make sure that the browser was loading all the scripts and css files, and it was. 

Am I missing something here or is this a bug?

**Comment by terrill** [comment]
Hi @afemath, this has been a known problem with Able Player searching in a particular (relative) directory for the translation files (which contain all labels, prompts, and other text). The workaround has been to add a **data-translation-path** attribute to your media element, pointing to the path of the translations folder. I just pushed a commit to the develop branch that should make **data-translation-path   ** in most circumstances: 7a5d276dfcbac1308dda300b355e1a4d321fae16

**Comment by afemath** [comment]
Thanks for the quick feedback! That was exactly what I needed.
