### ISSUE TITLE
Add support for metadata tracks

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#11]
http://www.w3.org/TR/html5/embedded-content-0.html#the-track-element

**Comment by kensgists** [comment]
Would like to revive this as a feature at some point. What about the data areas below the cue timings containing URLs?: A URL would load in a resizable window (like is used for sign interpreter track now). At the top of that window would be a toolbar with forward/back buttons, allowing the user to jump through the appropriately synchronized video/audio portion in the main window. 

A use case: Professor teaching calculus. The equation and notes from a web page load in the metadata window as the prof discusses a particular equation.

**Comment by terrill** [comment]
@kensgists in addition to URL support, and perhaps easier to implement in the short term, would be support for displaying hidden on-page content.  The content of each metadata cue could be a selector (e.g., id, class, HTML element). At the designated time, any matching elements could be set to display:block, with aria-live="polite" so the exposed content would be read by screen readers. 

With this in place, it would be up to authors to create and style the on-page content to match the metadata cues in their VTT file.  If the content is contained inside the same wrapper as the `<video>` element, the exposed content could appear as a video overlay. 

We could also add support for keywords within the metadata cue, such as: 
* pause = causes the video to pause at that point

**Comment by terrill** [comment]
Added support for jQuery selectors as metadata cues in 561f8df8fa6882af4f71303503090631c01575d9

@kensgists I'm closing this issue as complete. The player doesn't provide a window in which to view iframe content as you suggested. However, I see that as something the developer could provide. What this solution does provide is the ability to show and hide that custom content using jQuery selectors as metadata. Also by adding the one word "pause" on a line by itself within the metadata file, the video will pause as the new content is exposed, given users a chance to read the new content before resuming playback.  See Test7d and 7e for a couple of simple examples of this functionality in action.
