### ISSUE TITLE
Add caption control to YouTube wrapper

### ISSUE THREAD

**Issue by afemath** [ableplayer/ableplayer#110]
Why are there no captions for YouTube Videos? Even in your example there are no captions -> http://ableplayer.github.io/ableplayer/tests/test13.html. Is this feature coming soon?

**Comment by terrill** [comment]
Hi @afemath, the issue with YouTube captions is that they're hosted on YouTube and have to be toggled on via the YouTube site. They aren't exposed via the YouTube API so there's no way to control them in an external player. If a user has previously toggled captions on in the YouTube player, and they're using the same browser, then captions will appear within Able Player as well. 

The alternative would be to use a `<track>` element to add captions directly to Able Player. We don't currently support that but perhaps we should. The down side of doing that is if the video is already captioned on YouTube (which it should be), the user could end up with double captions.

**Comment by MichaelLockrey** [comment]
In the meantime if you looking for a way to handle YouTube captions (when the content owners don't do the right thing and provide captions) have a look at [nomoreCRAPTIONS] (nomorecraptions.com)

**Comment by afemath** [comment]
I noticed the following pages:

- http://stackoverflow.com/questions/13735783/youtube-api-how-to-use-custom-controls-to-turn-captions-on-off-change-languag
- https://developers.google.com/youtube/iframe_api_reference

It looks like there may be a way to do this. What do you think?

**Comment by terrill** [comment]
Definitely worth investigating further. Thanks @afemath !

**Comment by terrill** [comment]
Added in 43848d131af7a98407e9d1963d30a9e50ddd0e9c
