### ISSUE TITLE
pop-up dialogs for captions and chapters do not dismiss or fire properly in all cases

### ISSUE THREAD

**Issue by kensgists** [ableplayer/ableplayer#113]
Pressing ESC, making a change to an option, or clicking the button will dismiss the pop up option dialogs for chapters and captions. But clicking to open a dialog then clicking elsewhere in the player or on the page or even pressing another button on the player will not dismiss the dialog -- it stays visible. 

If I click another button or click outside of the pop-up dialog, the pop-up should dismiss.

Additionally, in a particular case, after dismissing the pop up option dialog, it takes two clicks to spawn it again. For example, on Test #7, click the captions button, then choose a new (non-selected) option ("no captions" for example). The pop up will dismiss and the focus will return to the captions button. But at that point, it takes two mouse clicks or Enter/Spacebar presses to re-spawn the captions dialog.

**Comment by terrill** [comment]
Fixed with 22b6461f3e72480d7651f491e49e6d5219fe38ab
