### ISSUE TITLE
Optional feature to allow controller to disappear

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#119]
There have been multiple requests for a controller that disappears after a few seconds, as is common with media players these days. So far we've resisted adding this feature for accessibility/usability reasons. The controls would need to be hidden in a way that: 
1. Keeps them accessible for screen reader users
2. Keeps them visibly focusable for keyboard users 
3. Keeps them operable with voice commands for speech input users 

Some users will need to have always-visible controls as a reminder of what controls are available. Otherwise, we're asking speech input users, keyboard users, and everyone else to remember the available controls and layout, which can be challenging especially if someone has cognitive issues that affect memory. 

I think we should add this feature as a Preference, but turn it off by default and allow users who are bothered by visible controls to enable it.

**Comment by terrill** [comment]
Add a fifth category to the Preferences menu "Controller", which for starters will have just one preference: 

* Hide controller when video is playing 

When user presses a key or hovers over the player, the controller will appear.

**Comment by zurisee** [comment]
I definitely support this feature.
To my mind a good solution could be rather simple: just reduce height (overflow: hidden) to the size of the preview image. Only on hover and focus the entire height would be shown.
If I'm not mistaken, accessibility should not be compromised as both screen-reader and keyboard users keep getting full access. At most, it takes one more click/tap to start the player.

**Comment by terrill** [comment]
User testing has revealed that this is an important issue for sighted users, including those whose disabilities affect their ability to tune out distraction. Multiple users report that the buttons are distracting and keep them from fully attending to the video. Escalating now to Top Priority Enhancement.

**Comment by terrill** [comment]
Added support for **data-hide-controls** in e8401165550939ad764f9688059a9231189dbfb9

Set to "true" to hide controls during playback. Controls are visibly hidden but still accessible to assistive technologies. Controls reappear if user presses any key or moves the mouse over the video player region.
