### ISSUE TITLE
Expose events to jQuery

### ISSUE THREAD

**Issue by gandalfar** [ableplayer/ableplayer#123]
Is there a way to access player from javascript? I'm trying to create jump to specific point in time button, outside of player.

Right now I've created new event, https://github.com/gandalfar/ableplayer/commit/c572cadf1051252195a63acf8b15524bc825d514#diff-6812b544765cd4d44ba3c4290f0808a2R6530 but maybe is there a better / official way?

**Comment by terrill** [comment]
There is no *official* way to pass an updated seek value to the player. I'm not sure whether there's a *better* way than what you've implemented. It seems like a good solution, but we need a method for passing data to a particular player if there is more than one player on a page. Also, in addition to passing a seek value we need to pass updated values of data-search so search results could be updated dynamically as users enter new terms in an external search field. 

I'm changing this to  "Enhancement - High Priority" as others have requested similar functionality.

**Comment by gandalfar** [comment]
I see several ways of doing this:

1. There is already `window.Ableplayer` - maybe have something like `window.Ableplayer.instances.playerid` would allow to cycle through player instances.

Ableplayer would in addition to that also proxy internal play/start/pause events using jQuerys `on` and namespaces. So you could then subscribe to events `ableplayer.pause` or `ableplayer.playerid` or `ableplayer.playerid.pause`

In addition to `instances` option, trigger `ableplayer.intialize` event for each player, with access to player internals.

2. Allow page authors to use data-callback and use `Function` to eval it, provide onInit access to internal objects.
I have no idea about sanity/security applications of this approach.

3. Allow initialization of player via Javascript and only support event/player control in this case.


I personally think that first option would allow to expand functionality without breaking existing code. Second isn't practical and third would require new public API.

**Comment by terrill** [comment]
Adding another use case just to be sure it's captured, courtesy of @mfairchild365: 
* Expose events such as when the video starts playing and ends (to log play counts)

**Comment by terrill** [comment]
One simple solution is to omit the **data-able-player** attribute from the media element, then assign a new AblePlayer instance to a variable on your web page. Then all Able Player functions are exposed and can be accessed via your custom JavaScript. I created a new test page (test19.html) that demonstrates this: See 919061b4224ddf747222444f3ee4dcbedbfab62c

**Comment by terrill** [comment]
Also, one can easily listen for any events exposed through the HTML5 media API - Able Player is not required for that. Again, see test19.html, which I've just updated with a simple example that listens for the "playing" and "ended" events: 1d1fff248c6c48cb367bc15d284d4aa4f5e3fa90
