### ISSUE TITLE
WebVTT cue text escapes are not supported

### ISSUE THREAD

**Issue by blrichwine** [ableplayer/ableplayer#126]
Cue text escapes ( http://dev.w3.org/html5/webvtt/#dfn-webvtt-cue-gt-escape ) are not being interpreted correctly. The parser simply drops the ampersand character. For instance, the &amp;gt; &amp;lt; &amp;amp; are displayed as gt; lt; and amp; instead of > < &amp;

This is particularly an issue since many captioning vendors represent speaker changes with two greater than symbols >> which ends up displayed as gt;gt;

**Comment by blrichwine** [comment]
.vtt file available upon request.

**Comment by blrichwine** [comment]
It looks like this is an easy fix. The parser has code to parse and handle making the text escape substitutions as appropriate. However, when parsing tokens in the data state, when it detects the start of a text escape it failed to set the tokenState to 'escape'.

I simply added the line
          tokenState = 'escape';
and it started handling the text escapes correctly.

I'm creating a video and webvtt file to use as a test for the text escape handling and will add them to a fork of ableplayer so you can pull it in if desired.

The tokenState line goes in ableplayer.js around line 1969:

      if (tokenState === 'data') {
        if (c === '&') {
          buffer = '&';
          tokenState = 'escape'; 
        }

**Comment by blrichwine** [comment]
I put in a pull request with changes to webvtt.js that handle the text escapes. Also, it adds a few lines so unescaped ampersands and unsupported entities show up as text.

**Comment by terrill** [comment]
Fixed in 849f7926cdba516544f6570eae5b0183814b3cce
Thanks @blrichwine
