### ISSUE TITLE
WebVTT styles

### ISSUE THREAD

**Issue by MireiaUB** [ableplayer/ableplayer#127]
Dear Terril and other contributors,

will it be possible to combine ableplayer with playr features?

http://www.delphiki.com/html5/playr/

Playr shows cue styles very well.

Regards,
Mireia

**Comment by terrill** [comment]
We intend to support WebVTT cue styles. That's issue #13

**Comment by terrill** [comment]
Closing this issue for now in order to keep the issue queue manageable. @MireiaUB if there are other features of playr that you'd like to see integrated into Able Player feel free to create new issues for feature request. Thanks!
