### ISSUE TITLE
JWPlayer fallback image should be inside playlist

### ISSUE THREAD

**Issue by gandalfar** [ableplayer/ableplayer#128]
With latest JWPlayer poster image doesn't work. This fixes it:

         this.translationPath = this.rootPath + '/translations/';
    @@ -736,11 +735,11 @@
             if (thisObj.mediaType === 'video') {
               thisObj.jwPlayer = jwplayer(thisObj.jwId).setup({
                 playlist: [{
    +              image: thisObj.$media.attr('poster'),
                   sources: sources
                 }],
                 flashplayer: flashplayer,
                 html5player: html5player,
    -            image: thisObj.$media.attr('poster'),
                 controls: false,
                 volume: thisObj.defaultVolume * 100,
                 height: jwHeight,

Sorry for inline .patch. I still haven't figured out line endings.

**Comment by terrill** [comment]
Excellent, thanks @gandalfar 
Fixed in 0b69a91c21f6da6d01940fce42c12fe6a637f6d2
