### ISSUE TITLE
Transcript highlights don't seem to work on pages featuring multiple players with transcripts

### ISSUE THREAD

**Issue by rtrvrtg** [ableplayer/ableplayer#129]
Hi,

I've been working with Ableplayer a little while and think it's really well done and provides much-needed support for accessible players. However, I think I've hit a weird bug that directly affects a use case I have in mind for it. The issue is that on pages that show multiple players, only one of the players shows highlights at all. While the other players play back just fine, they never show highlights at all.

I think the root of the issue might be in [AblePlayer.prototype.highlightTranscript](https://github.com/ableplayer/ableplayer/blob/a74f9520b4be4ad8ccd018fb7cdb5011c3f84860/scripts/transcript.js#L72), because I noticed that while jQuery selectors are used to pick out elements to highlight, that selector doesn't actually specify a containing transcript element, or limit its scope to a particular transcript element. If these selectors got adjusted so that Ableplayer is aware of the current transcript scope that it is working with at the time, it should be able to support a highlight for each player.

I should be able to take a crack at putting together a pull request to tackle this issue, but I figured that I should ask if you or anyone who uses Ableplayer had noticed this first. Thanks for your time!

**Comment by terrill** [comment]
@rtrvrtg this was actually more than just highlights. With multiple transcripts present clicks and keydown events weren't being correctly handled either. Should be fixed now in 889d793f347413b3295a1df93b6dc5754733feb1
