### ISSUE TITLE
Examples for plugins and extending functionality

### ISSUE THREAD

**Issue by mfairchild365** [ableplayer/ableplayer#130]
I haven't seen anything regarding this in the documentation.  If I have simply missed it, please let me know.

Does ableplayer support any of the following?
* custom themes
* custom buttons (for sharing the video or other custom functionality)
* does it expose events such as when the video starts playing and ends (to log play counts)

**Comment by terrill** [comment]
@mfairchild365 we've talked about creating custom skins so users have a few choices, but to my knowledge nobody has taken steps yet to pursue that.  Meanwhile, the look and feel is fairly customizable via the CSS files.  

As for exposing events, that's on our todo list: #123
