### ISSUE TITLE
Native captioning in some browsers not disabled resulting in doubled caption presentation

### ISSUE THREAD

**Issue by blrichwine** [ableplayer/ableplayer#141]
If the Chrome browser (windows or mac) has show captions enabled, then those captions will be present along with the captions AblePlayer is presenting. See image.
![chromedoublecaptioning](https://cloud.githubusercontent.com/assets/1859574/8423084/1945fcce-1eb2-11e5-802a-903e8be0d5a4.jpg)

**Comment by terrill** [comment]
This is an issue that we thought we had fixed many times, but continues to resurface. See #5 for background.

**Comment by terrill** [comment]
@blrichwine or @sebastiankelle what are the steps for replicating this problem? 

In Chrome 46.0.2490.86 (on Mac) I'm not seeing duplicate captions. "Show captions" seems to be enabled, based on the fact that captions are displayed in test0.html, which is just the native media player without Able Player.  But when viewing Able Player tests in Chrome, I only see the Able Player captions, not Chrome captions. 

Was this perhaps a temporary bug in Chrome that has now been fixed?

**Comment by terrill** [comment]
Also tested in Chrome 46.0.2490.86 (on Windows). I'm still not able to replicate this problem.

**Comment by terrill** [comment]
Closing this issue, unable to replicate. If anyone observed this again please reopen the issue and comment with as much detail as possible about the environment you observed it in (browser, version, OS & version, etc.)

**Comment by terrill** [comment]
Reopening this issue - I'm observing duplicate captions now in Safari on an iPAD in iOS 9.2.

**Comment by terrill** [comment]
Fixed in Safari 10 via b39d5340b2a590625f4249b9d459ac9a25bcb72b

**Comment by terrill** [comment]
The solution that seemed to fix this problem in Safari 10 stopped working in Safari 11.  The standard solution is to [set textTrack.mode to disabled](https://developer.mozilla.org/en-US/docs/Web/API/TextTrack/mode), which instructs the browser to ignore the text tracks and let Able Player handle them. Previously, this was found to be a timing issue, and was solved in Safari 10 by waiting to call setMediaAttributes() - the function that sets textTrack.mode to disabled - until after setupTracks() was finished.  Sometime later (observed in Safari 11) the bug returned, and was again found to be a timing issue. Apparently Safari ignores the instruction to set textTrack.mode to 'disabled' until it's ready to receive that request. I don't know how to know whether it's ready, but it seems to be solved (again) by waiting even longer to call setMediaAttributes(). In 5c827d6cf1e2bb4e083cbc06c4ca618a87ffdb31 we're waiting to call that function until the very end, after initPlayer() is complete. 

If this problem resurfaces again, a more aggressive solution might be to remove the &lt;track&gt; elements from the DOM altogether after Able Player parses them.
