### ISSUE TITLE
No Poster or Big Play Button when YouTube clip

### ISSUE THREAD

**Issue by lukemunn** [ableplayer/ableplayer#143]
When using Able player to play YouTube clips, I have the following problems:

- Poster (still image before pushing play) doesn't appear, or appears for a second before getting 'overwritten' with a pure black screen

- Big Play button (which appears on ogg, self hosted clips, etc) doesn't appear either

Both of these behaviours can be viewed on Able's own demo page for YT embeds
http://ableplayer.github.io/ableplayer/tests/test13.html

**Comment by lukemunn** [comment]
Ah just saw issue #139 . Yes personally I would love to just use YouTube's stored stills for each video, to avoid manually doing a screengrab, upload and linking of a Poster image.

**Comment by terrill** [comment]
Thanks for the feedback @lukemunn . I'm closing this issue to keep the queue clean, but your vote for #139 has been noted.
