### ISSUE TITLE
Closing the Preferences dialog doesn't really close it

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#144]
If a user makes changes within the Preferences dialog then clicks Cancel or the X button, the dialog is hidden from view, but is still present in the DOM with the selected options still selected. Thus if they request the Preferences dialog again, it shows all checkboxes in their most recent state, even if that differs from the actual saved state. This is likely to confuse users. 

I think there are one, maybe two, needs related to this: 

1. When the dialog is closed without saving, all options should be restored to their current saved state. 
2. (maybe) If users have made changes and close the dialog without saving, they should be warned that they are about to lose their changes and given opportunity to confirm (which closes the dialog) or cancel (which returns focus to the dialog without closing). I'm on the fence as to whether this is necessary. I know it's a good practice for forms where users have entered information, but in this case it's just a few checkboxes so it might be more burdensome than helpful. Any opinions?

**Comment by zurisee** [comment]
Re. 1. I agree
Re. 2. I lean towards informing the user as I stumbled over this myself. At least when closing the Preferences dialog via the close button in the upper right corner. For the Cancel button it's not necessary, though - somebody clicking on that should be sufficiently aware of what's going to happen.

**Comment by terrill** [comment]
Functionally fixed with 68068606ebd18ca10cbcafd70761ecb952839eef

If user cancels, closes the dialog, or escapes, the default settings are now restored. 
The additional feature of prompting the user if they've made any changes is now a new issue #177.
