### ISSUE TITLE
Replace jquery.cookie with js-cookie

### ISSUE THREAD

**Issue by jcoyne** [ableplayer/ableplayer#147]
According to the github repo https://github.com/carhartl/jquery-cookie jquery.cookie is no longer maintained and has been superseded by js-cookie https://github.com/js-cookie/js-cookie

**Comment by terrill** [comment]
Complete with d99ef84397b5fd48c9f066d32ebd9d6be43222dc
Tested in Firefox and Chrome on Mac; and Firefox, Chrome, and IE on Windows

**Comment by Aybee** [comment]
Please change text in README.md
Headline: Setup Step 2: Add JavaScript and CSS
**jquery.cookie.js => js.cookie.js**
