### ISSUE TITLE
What is the purpose of `sn5rkg`?

### ISSUE THREAD

**Issue by jcoyne** [ableplayer/ableplayer#149]
https://github.com/ableplayer/ableplayer/blob/1a5eeda422beae759faf15e7e29609fdf16d36f4/styles/ableplayer.css#L436

**Comment by terrill** [comment]
That's the CSS that was provided by [icoMoon](https://icomoon.io/) when I downloaded the font set. I just copied and pasted without asking questions. Should I have asked questions @jcoyne? Do you have concerns about it, or are you just curious?

**Comment by jcoyne** [comment]
Just curious. I had to make a change to the font path locally (to serve the assets with Rails) and I wanted to understand the importance of that.
