### ISSUE TITLE
The Show Transcript control is visually indicated as active by default even when transcripts are not displayed

### ISSUE THREAD

**Issue by blrichwine** [ableplayer/ableplayer#152]
The visual state and alt text indication of the show/hide transcript button is set to the wrong state at startup. This can be seen here:

http://ableplayer.github.io/ableplayer/tests/test7.html

* The show transcript button is bright (should indicate transcripts are on) when the page first loads
* Click the show transcript button and the transcripts appear, and the show transcript button remains bright.
* Click the show transcript button a second time, and the transcripts disappear and the show transcript button becomes dim

The state of the show transcript button needs to be tied to the state of the transcript's visibility at first rendering instead of on by default (as exhibited by the CC and Description controls).

**Comment by terrill** [comment]
Fixed with 583cbd5675b2c98246f38fea64533fc3c3311019
