### ISSUE TITLE
Change main video speed doesn't affect sign language video

### ISSUE THREAD

**Issue by wang0109** [ableplayer/ableplayer#154]
Tested at: http://ableplayer.github.io/ableplayer/tests/test16.html

The sign language video should change as well, to be in sync with the main video.

This was reported in Dr. Socha's email earlier.

I intended to try and solve this issue. However, I am just getting started learning Javascript, HTML5 and the ableplayer codebase.

**Comment by terrill** [comment]
Thanks @wang0109 - I intended to add this to the issue queue but hadn't gotten to it yet. Thanks for the nudge! Should be an easy fix.

**Comment by terrill** [comment]
Fixed in 44533064580ccd4b20f2ab0a24ff9d2d3b0d7e44
