### ISSUE TITLE
Is it possible to have lyrics/captions for each file in an audio playlist?

### ISSUE THREAD

**Issue by dsplzion** [ableplayer/ableplayer#156]
It's probably possible. I'm just not sure how you would do it and the examples don't show.

thanks

**Comment by terrill** [comment]
Great question @dsplzion!  Unfortunately that's not supported currently, but should be. I just created a new issue #157

**Comment by dsplzion** [comment]
Thank you.

**Comment by terrill** [comment]
If you have feedback on the idea proposed, please share. Otherwise I'll get started working on it sometime in the next few weeks.
