### ISSUE TITLE
Create a WordPress plugin

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#158]

**Comment by sposhe** [comment]
@terrill thanks for the work you've put into this so far—look like a great tool. Looking at using this within WordPress site in the near future, and wanted to see if there has been any progress on the plugin front?

**Comment by terrill** [comment]
Slow progress, not quite ready to share yet.
I'm targeting having something available in time for the CSUN Conference,
on or around March 21.

Thanks for your interest!
Terrill

**Comment by sposhe** [comment]
Thanks for the update!

**Comment by terrill** [comment]
A new WordPress plugin repo has been created here: 
https://github.com/ableplayer/ableplayer-wordpress
