### ISSUE TITLE
Incompatible with ZoomText Screen Magnification software and the Firefox Web Browser

### ISSUE THREAD

**Issue by blrichwine** [ableplayer/ableplayer#159]
When ZoomText is installed on a system, the ZoomText installer drops a config file into the ../Mozilla Firefox/defaults/pref folder which sets gfx.downloadable_fonts.enabled to False. I'm not sure if anything can or should be done about this, but it may be worth mentioning in the docs as a known issue and how to resolve it (change the setting back to true).

The result of using AblePlayer in Firefox on computers with ZoomText installed is the following:
![image](https://cloud.githubusercontent.com/assets/1859574/10496992/8b89abe0-7291-11e5-8a02-fc941ed43c51.png)

**Comment by terrill** [comment]
Good catch @blrichwine. Currently in initialize.js > function setIconType() we're using window.getComputedStyle to identify whether browsers support icon fonts. If that test fails, or if the browser is IE8 or earlier, the icon fonts are replaced within images. Not sure if it's possible to detect whether gfx.downloadable_fonts.enabled is set to False, but that would be the place in the code to do it.

**Comment by sebastiankelle** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1121910: seems it was resolved in latest version of ZoomText. That doesn't mean we couldn't try to check for gfx.downloadable_fonts.enabled in the code but I'm not exactly sure how to check that preference as it's a local setting in the browser's about:config setting. Any clues would be welcome.

**Comment by terrill** [comment]
Closing this old bug. I think it's no longer an issue. Just tested with Zoomtext 2021 in Firefox 95 with Able Player set to use icon fonts via **data-icon-type="font"** – the font icons are all visible. Also, Able Player has been using SVG icons by default for many versions now.
