### ISSUE TITLE
Player not restored to correct width after full screen in Opera

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#162]
When pressing Escape to exit full screen mode in Opera, player is no longer in full-screen mode, but it still retains its full-screen width (too wide to fit within a web page). 

This only happens if the user presses the Escape key. Clicking the "Exit full screen" button, the player is restored correctly to its original size. 

I observed this in Opera 32 on Mac OS X. I double-checked Firefox, Chrome, & Safari on Mac; plus IE11 in Windows, to see if this was in issue in any other browser and didn't observe it anywhere. Seems to be unique to Opera.  

![ableplayer-opera-after-fullscreen-escape](https://cloud.githubusercontent.com/assets/912874/10581739/1eb4e920-7639-11e5-9363-868f1021143a.png)

**Comment by sebastiankelle** [comment]
Could not reproduce this with Opera 33.0 64bit, run on a windows 10 pro system. Escape correctly resizes back to normal...

**Comment by terrill** [comment]
Still a problem with Opera 33 on Mac OS X 10.11.1 64-bit. However, it does **not** happen if Opera DevTools are open (which makes it challenging to debug)

**Comment by sebastiankelle** [comment]
OK i'm still not able to reproduce the bug in my environment. How should we go forward?

**Comment by terrill** [comment]
Fixed with fa943da7bdfd662adc74aa3ae757b87dad776ae4
