### ISSUE TITLE
Play and Pause button toggling - Hence video not playing

### ISSUE THREAD

**Issue by pmjaleel** [ableplayer/ableplayer#170]
Hi Team,
Video is not playing because the play and pause button event is firing by itself. In order to debug the issue we did the following:
1) Downloaded the sample video of able player and it worked
2) Downloaded the video that we are trying to play via typing the URL in the browser. Deployed it in the web server folder and gave the http URL to that video which is locally placed. It worked as well.

Now we are unsure on where the issue has to be tracked.

**Comment by sebastiankelle** [comment]
Hi. Did you get this problem on the master or develop branch? I'm in the middle of fixing bug #163

**Comment by pmjaleel** [comment]
While debugging the JavaScript, we found few clues one of them worked. By default the description is off. It is then that this issue occurs. When we turn on the description we get the video played.

**Comment by pmjaleel** [comment]
Is there a problem if we have the 'source type' tag as below:
 <source type="video/mp4" src="@story.VideoUrls[0]" data-desc-src="@story.VideoUrls[0]" />

**Comment by pmjaleel** [comment]
Hi Team,
I have used the files from both the branches. We are having tough time getting the functionality right.
1) Auto play not working - even after providing the attribute.
2) Transcript not highlighting, video does not move while clicking the transcript section

We are using the player in ASP.NET MVC

**Comment by pmjaleel** [comment]
We found the issue. This was due to the format error in the WebVtt that we were linking.
