### ISSUE TITLE
Youtube Player does not start playing when you click play

### ISSUE THREAD

**Issue by botto** [ableplayer/ableplayer#172]
The youtube plugin does not seem to be playing the video when you click play. The only way is to drag the slider a couple of seconds forwards at which point it will start playing.
I'm guessing it's a change in the yt API

The youtube example pages shows this https://ableplayer.github.io/ableplayer/tests/test13.html

This was tested with Chrome and Firefox on Linux

Thanks to @lopezs for finding this

**Comment by Thorn323** [comment]
I am having the same problem. Tested with Firefox on Windows.

**Comment by terrill** [comment]
Fixed in b3269fdba9a1168faa1d25f5972ba661aefae1ba
