### ISSUE TITLE
Does ableplayer support multiple transcription with playlist?

### ISSUE THREAD

**Issue by ravinderk** [ableplayer/ableplayer#190]
I find that ableplayer supports video playlist. Can you point me in right direction to load new transcript file and other settings for each video file in playlist.

**Comment by terrill** [comment]
Currently that isn't supported, but it's a high priority and we expect to add this capability soon: 
https://github.com/ableplayer/ableplayer/issues/157

**Comment by ravinderk** [comment]
Thank you Terrill

**Comment by terrill** [comment]
Playlist support is now much-improved as of c0d291c70fd5b8be5879c6fef362407c699c17c3
