### ISSUE TITLE
Disable Preferences icon

### ISSUE THREAD

**Issue by kishkool** [ableplayer/ableplayer#207]
Hi,

I would like to get get the most simple esthetic video player.
How can i remove Preferences and Help button?

Thank you.

**Comment by terrill** [comment]
@kishkool the Help button has been eliminated in the latest version on the develop branch: 
https://github.com/ableplayer/ableplayer/tree/develop

That will be moved over to the master branch soon and released as v2.4 (a few other updates in the works between now and then though). 

We've also taken some other steps to unclutter the interface, including consolidating the three volume buttons into a single button that triggers a vertical slider when clicked. 

As for Preferences, that button can't be removed as user choice is an integral part of what makes Able Player accessible.

**Comment by kishkool** [comment]
Hi,
Sound great, thank you for your feedback.
Given that i really need for now to hide "Préférences" and "Help" i've just hide the dedicated icon on css.
icon-preferences
icon-help
It does the trick for now.

Thank you anyway.
