### ISSUE TITLE
Some suggestions on icons directory.

### ISSUE THREAD

**Issue by motchie** [ableplayer/ableplayer#221]
After `images` directory changed into `icons` directory, I had some trouble with player buttons.

To get straight to the point, it was caused by Apache’s default `icons` directory alias was conflicted.
http://www.apache.org/icons/

Able Player searched UI icons into Apache’s `icons` directory, but there were no `play.png` and so on.

Of course, it was my mistake on my server settings, but I spent several hours using JavaScript debugger and so on.

So, to avoid the future trouble, how about changing icons directory name into more complex name like `toolbar-icons`?

**Comment by terrill** [comment]
Renamed to `button-icons` in c9e12198b67259703c26bd6aae3c0302c957415f
