### ISSUE TITLE
Broken buttons layout when adding track element.

### ISSUE THREAD

**Issue by motchie** [ableplayer/ableplayer#222]
Hi @terrill ,

In develop branch, when I add following track element to `/demos/local_ja.html`, just after Espanol captions, the player buttons layout were broken(Big Play icon placed in wrong position, and buttons are gone).
.
```<track kind="captions" src="../media/wwa_captions_ja.vtt" srclang="ja" label="日本語" default/>```

![add-ja-caption-element](https://cloud.githubusercontent.com/assets/158450/15372422/4c6a7594-1d7b-11e6-86a6-fab777e00e09.PNG)

I'm also confirmed that same thing happened when adding `track` element with `kind="descriptions` attribute.

Is there are some requirements when adding  `track` elements?

Thanks.

**Comment by terrill** [comment]
@motchie are there any errors in your browser's developer console?

**Comment by motchie** [comment]
@terrill I'm sorry, it's  maybe because of missing actual file.

![js-error](https://cloud.githubusercontent.com/assets/158450/15378027/f9fad95a-1d9a-11e6-9cb5-6d3d28b6a503.PNG)

**Comment by terrill** [comment]
Yes, that's definitely it. Any Japanese `<track>` element you add will need to have a corresponding translated file in the `/media` directory. 

Are you planning to submit a pull request today with more Japanese demo content? I'm about ready to merge all of the recent changes into the master branch and release a new version. But if you're about to submit a pull request I can wait.

**Comment by motchie** [comment]
OK, I'll PR additional captions in 2-3 hours.

And today, in GAAD day, l'll demonstrate
Japanese version of Able Player to Japanese a11y forks!

http://accfes.com/seminar_page09.html

**Comment by motchie** [comment]
Done! https://github.com/ableplayer/ableplayer/pull/223

**Comment by terrill** [comment]
Excellent!  Happy GAAD!
