### ISSUE TITLE
Add support for synchronized sign language

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#23]
This requires discussion. 

HTML5 doesn't support synchronized sign language with &lt;track kind="signlanguage"&lt; or anything similar. So this will have to be custom solution involving two &lt;video&gt; elements that are explicitly connected somehow. Perhaps we could add an attribute like **data-sign="sign_id"** where **sign_id** is the id of the companion video. 

The companion video should just be a video with no controller, and its operation should be synchronized with the main video player. 

Where to position the companion video would require some experimenting and user testing. I think a floating-on-top, resizable div would be nice so users have total control. 

NOTE: There is already a sign language button added to the controller if this.hasSignLanguage is true.

**Comment by terrill** [comment]
Sign language in moveable, resizable window is now supported as of 8da3b9a592aaa4c922184d3515fa65bf95601fc3

**Comment by Egyrs** [comment]
Bravo! I'm so happy :-)
