### ISSUE TITLE
Question:  support for WebVTT cues with multiple lines and other new parts of the standard?

### ISSUE THREAD

**Issue by KimPatch** [ableplayer/ableplayer#237]
Are you planning support for other WebVTT features including cues with multiple lines using just a line break? 
https://w3c.github.io/webvtt/#introduction-multiple-lines

**Comment by terrill** [comment]
Ultimately we would like to **fully** support WebVTT, but I'm hesitant to put much effort into that currently since the standard is still evolving.  I do like that multiple lines feature though! 

Here's the relevant catch-all issue: https://github.com/ableplayer/ableplayer/issues/13
