### ISSUE TITLE
Default CC off

### ISSUE THREAD

**Issue by pmjaleel** [ableplayer/ableplayer#239]
I need the Closed Caption to be off by default. How do I do that?

**Comment by terrill** [comment]
It currently isn't possible for the developer to set "off" as the default state of captions. If captions are available, they're on by default. This is based on the belief that captions being on is a **need** for some users, whereas captions being off is a **preference** for some users, and needs should override preferences. If a user turns off captions, the player **should** save that preference and honor it until the user turns captions on again. In other words, users only need to turn captions off once, then they'll be off by default for all subsequent videos from that site. That said, this doesn't seem to be working at the moment. I've tagged this as a bug and will fix it soon.

**Comment by terrill** [comment]
The bug that was preventing user preferences for caption state from being saved has been fixed in 9f4cf19ff26ec376487d31a7ae57cad5d9a94700

Now, if a user turns off captions, they will always be off as long as there's an active cookie in the user's browser.
