### ISSUE TITLE
Italics again

### ISSUE THREAD

**Issue by roberttucker** [ableplayer/ableplayer#242]
Can anyone please point me to a site where italics are working with Able Player?

I have a site where I have italics working with the kludge I described here some months ago:

http://kinomovi.site88.net/kh.html

But I still do not find italics to work with the since modified versions:

http://kinomovi.x10host.com/de/pages/mv/0001.html
http://kinomovi.x10host.com/de/pages/mv/0003.html

(Both these movies start with offscreen narration where I use italics.)

http://kinomovi.x10host.com/de/subs/mv/en/0001.vtt
http://kinomovi.x10host.com/de/subs/mv/en/0003.vtt

**Comment by terrill** [comment]
@roberttucker the English caption file that's included in the collection of [Able Player Examples](http://ableplayer.github.io/ableplayer/demos/index.html) includes both `<i>` and `<b>` tags. The italics is converted to `<em>`  and the bold is converted to `<strong>`. Both appear as expected in both the captions and transcript. For example, see [Video Demo #1](http://ableplayer.github.io/ableplayer/demos/video1.html) (the word _want_ in the first sentence is italicized).   

On your site, if you look at the HTML code that's being rendered (either in the captions or transcript), you'll see that the italicized content is in fact tagged as `<em>`, so this is a CSS problem. Somewhere you have a style declaration that's overriding the browser default for em. Try adding this to your style sheet and see if that fixes the problem: 

```
em { 
  font-style: italic !important;
}
```

**Comment by roberttucker** [comment]
Oh, I think I remember seeing that now in the examples.

Yes, adding that to the CSS that has fixed it, thank you. The CSS came with the template, of course.
