### ISSUE TITLE
How to remove some options from the control bar (like show transcript or change the speed of the video) ?

### ISSUE THREAD

**Issue by gama41** [ableplayer/ableplayer#245]
Hello, 

I need to remove some option of the player like "show transcript" or "change the speed of the video".
How can I proceed to remove them please ?

**Comment by terrill** [comment]
@gama41 see the [README](https://github.com/ableplayer/ableplayer/tree/develop) file under Transcript for options for how to deliver the transcript. To remove the button from the player use data-include-transcript="false".  

The speed controls can be set to either data-speed-icons="animals" or data-speed-icons="arrows" but they can't be removed. Why do you want to remove them? Being able to slow down the video plays a key role in accessibility, and being able to speed it up is hugely popular among time-impaired users as they can watch a video much more quickly without skipping content.
