### ISSUE TITLE
multiple play buttons/songs but only one player

### ISSUE THREAD

**Issue by anybany** [ableplayer/ableplayer#246]
Hi, i've got some crazy idea in mind and would like to ask for it :)

I would like to build a website with one player (play/pause, progress, volume etc) fixed somewhere on the page and then multiple play-buttons spread all over the page. and each play-button starts a different song in the fixed player.

do you think something like this is possible with ableplayer?

nevertheless ableplayer looks awesome and seems to be very easy. i will try it on the weekend!

**Comment by terrill** [comment]
@anybany that sounds do-able - see the [Able Player API demo](http://ableplayer.github.io/ableplayer/demos/video13.html) for an example of how to control the player with external buttons and controls. When a user clicks one of the play buttons, you'll need to swap the media source file, then listen for the 'canplaythrough' event before calling the playMedia() function.  

Good luck! And please share when you have it finished - it's an interesting idea!
