### ISSUE TITLE
How to change the volume bar orientation from vertical to horizontal in audio player?

### ISSUE THREAD

**Issue by cesarodriguez4** [ableplayer/ableplayer#247]
Customizing the aspect of the audio player I need to rotate the orientation of the volume bar for fit in my design.

![captura de pantalla de 2016-09-14 16 39 04](https://cloud.githubusercontent.com/assets/11139209/18529175/08f8dbbc-7a9a-11e6-891e-08a63c34284a.png)

Is there a easy way to change the orientation of the volume bar? If not, can you explain me how Can I do? I need to change it, it's a requirement.

**Comment by terrill** [comment]
@cesarodriguez4 there's no **easy** way to change the orientation of the volume slider. You could  probably change it by changing relevant styles within styles/ableplayer.css, but there would also probably be some modifications required within scripts/volume.js. For comparison see scripts/slider.js - that's an accessible horizontal slider by default and you could use that as a model to guide your modifications to volume.js. If you succeed, it would be nice to make it optional with something like a **data-volume-orientation** attribute which is either "vertical" or "horizontal". Then you could contribute this option back to the main repo so others can use it.

**Comment by cesarodriguez4** [comment]
Well, I'll contribute adding a horizontal orientation the the volume bar, in a few days will pull the changes into a new fork for all the community. Regards.
