### ISSUE TITLE
Player never loads

### ISSUE THREAD

**Issue by sprousecu** [ableplayer/ableplayer#248]
Hi, I just downloaded and unzipped ableplayer from https://ableplayer.github.io/ableplayer/ and when I try the demos in IE-Edge, FF 45.0.2, or Chrome  52.0.2743.116 m the video loads (eventually) but the player never does. I've tried demo1, 3 and 4.  They work fine on the gethub site, however.  Do I need to set anything up before I can at least run the demos? I didn't find anything in the read me file about running the demos, so I presume one just runs them. If I view the html of those files, they appear to have appropriate paths for the webm and vtt files.

Appreciate any help to get me started.  I'm hoping to replace the flash player we use for our custom courses in the university's LMS for faculty and staff.

**Comment by mbar196** [comment]
As far as I kow, the player does not run locally. I think you have to run the files from a webserver. 
Michael

**Comment by sprousecu** [comment]
@Michael,  I hope that's not the case. If so, we aren't going to be able to use ableplayer since we cannot implement through a webserver for our situation. 

Meanwhile, I've been experimenting with the problem by changing the jQuery dependency in the html files from 1.8.2 to the most current version 3.1.0 as shown below:  

In Adobe Brackets' Live Viewer this appears to work on both audio and video though the player is still having issues in FF, IE and Chrome.

Here's what I've changed thus far:


<script src="../thirdparty/modernizr.custom.js"></script>

<script
			  src="https://code.jquery.com/jquery-3.1.0.min.js"
			  integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="
			  crossorigin="anonymous">
</script>     
<script src="../thirdparty/js.cookie.js"></script>

**Comment by terrill** [comment]
@sprousecu it's true that Able Player was designed with the intent of playing audio and video files on the web, not local files on the user's computer.  Browsers don't like giving web pages access to local files for security reasons. We could probably have developed workarounds for that but didn't anticipate having a need. What exactly is your use case? Can you run a web server on your local computer using a tool like [XAMPP](https://www.apachefriends.org/download.html)? If so all you would need to get Able Player to work without Internet access would be a local copy of jQuery.

**Comment by sprousecu** [comment]
@Terrill
Here’s a brief overview of my case. My department provides training for all of our staff and employees of our four campuses through  SkillSoft’s learning management system, LMS. Currently, when video is included in a course, we use a flash-based player I created years ago to allow for closed-captioning and keyboard control. As flash is becoming more and more of a problem and our player barely addresses accessibility in the first place, I am trying to find an accessible player we can use.
Able Player looks like it could be a solution if I can solve two issues: figure out how to deploy it on the SkillSoft LMS; minimize its footprint.  I doubt we can convince SkillSoft to host the player on their LMS, so I’ll need to talk to our university information systems department to see if they can help me come up with a solution. Perhaps we can host the player on one of our system machines and call it from within the course that will reside on SkillSoft. Do you think something like that might work?

Meanwhile, I’ll load that tool on my computer so that I can test Able Player in our courses while they are in a local environment.
I hope to see you at the AHEAD conference in November.  I believe I saw that you were presenting again this year.

Thank you,
David Sprouse

**Comment by terrill** [comment]
@sprousecu I don't have any experience with SkillSoft but I think what you're proposing should work. If you get it working please share!  See you in Colorado.

**Comment by sprousecu** [comment]
Update,  We're making some progress here. The universities IT support team recently loaded able-player on a public server so we can now launch videos using FF and Chrome on both PC and Mac, but not Safari (no surprise there) or IE.   Trying to figure out why IE doesn't work at this time.  We've applied the mime types to our server, but still neither the .mp4 or .webm files launch. 
In our LMS environment Able Player appears to loads:  the videos won't play but the transcription files load. Directly on my development machine Able Player doesn't appear to load at all in IE only. I get the overall framework, but no buttons.  I find that very odd.

**Comment by sprousecu** [comment]
Final Update.  Apparently spelling counts. Who knew ;-) I'm feeling foolish, but I know I'm not the only one to make such a mistake. The file name for my mp4 was incorrectly spelled. This is now working on our SkillSoft LMS for all my browsers on both Win 7 and Mac OS-10.11.6
