### ISSUE TITLE
Safari 10 unable to tab focus controls

### ISSUE THREAD

**Issue by joe-watkins** [ableplayer/ableplayer#253]
After upgrading to Mac Sierra 10.12 I noticed I was unable to tab to the video controls. The focus jumps outside of the browser when trying to tab through the document. This was not happening for me in Safari 9.

It looks like it reaches the `<video>` element or close to and jumps out.

Here is a [video screencast](http://www.screencast.com/t/Y4tmlREJsBxT)

**Steps to reproduce**
1. Visit http://ableplayer.github.io/ableplayer/demos/video2.html in Safari 10
2. Tab through the interface to controls

**Comment by joe-watkins** [comment]
I noticed if you click on a control or in that area you can then access the controls with keyboard. Just can't get past `<video>` when tabbing through the content.

**Comment by joe-watkins** [comment]
I also noticed the YouTube example does not have seem to have this bug in Safari 10: http://ableplayer.github.io/ableplayer/demos/youtube.html

**Comment by terrill** [comment]
The difference between YouTube vs. not provides an interesting clue. I'm at a conference this week and unable (unwilling) to upgrade my production MacBook, so I won't be able to investigate further until next week.

**Comment by joe-watkins** [comment]
@terrill Tnx much for the update! I will poke at it some more in the meantime :)

**Comment by deadmanhead1602** [comment]
I am using EI Capitan + safari 10.0 . Same issue happens.

**Comment by terrill** [comment]
@deadmanhead1602 I've been trying to figure out **why** your solution works, but frankly I'm stumped. In any case, it does work so I've added this fix in  9f0f0834fa504396764987c053b9f801780633c1

**_Thanks!_**
