### ISSUE TITLE
Volume Slider erratic w/ YouTube Player

### ISSUE THREAD

**Issue by brunetgarcia** [ableplayer/ableplayer#270]
The volume slider drag behavior does not function as expected when playing YouTube videos. The range is limited and dragging is erratic. Keyboard controls behave as expected.

This issue is present on http://ableplayer.github.io/ableplayer/demos/youtube.html (master & develop #c988c19). 

Behavior is reproducible on the following tested browsers using BrowserStack.
Chrome (latest)
Firefox (latest)
Edge (latest)
Safari 9+
IE 10 & 11  (IE10 requires [MutationObserver polyfill](https://github.com/megawac/MutationObserver.js) to control YT)

**Comment by terrill** [comment]
Fixed in b070e2896a1cf86f3d881f46ad4526672f4cd9e6
