### ISSUE TITLE
Any Advice on button customization features

### ISSUE THREAD

**Issue by Gymboree** [ableplayer/ableplayer#275]
Hello Sr.

Good day.. I was kinda hoping to customize the Able Player buttons and some other features. I was trying to edit the ableplayer.js and the ableplayer.css.. Would it be possible to call the functions of ableplayer.js in the html? for example I want the transcript of Able Player in the html not embed in the player. 

What would I do with this or can you give me a little advice or an idea on how to implement this? I really love the functionalities of the player and I want to customize it... Please I need advice.. Thank you so much..

**Comment by slinhart** [comment]
Hey @Gymboree could you give more details? Why do you want the transcript in the html?

**Comment by Gymboree** [comment]
@slinhart  How are you! Thank you for replying. I really appreciate it.

I want to customize the functionalities of the player. Like for example the transcript features. I want to put it in html not inside the the video. For example I want to put the play button, the restart, captions, etc. outside or not just under the video but any place in the html. In other words customizing it and put the buttons wherever I want. I really need help with this I was having research for weeks now in depth JavaScript advanced design patterns approach and fundamental role in modern JavaScript. Still I'm still confused on how to implement my customizations.

I'm a dev my self but I'm more focus on back-end. I'm not new in front-end but this one I think is hard for me. I'm not yet very good in JS but with this I believe I can learn new things and I love the functionalities of this player so awesome. I want to customize it and maybe help develop this application. I really need advice since this one has only few research partners and no community. I'm very lost here. Thank you so much for your reply.. Really need help.

**Comment by terrill** [comment]
@Gymboree Able Player's functions can be accessed via external controls. Have a look at [Video Demo #13](http://ableplayer.github.io/ableplayer/demos/video13.html).

**Comment by Gymboree** [comment]
Hey there @terrill . Thank you for the reply. Oh I see now. Thank you for this. 
I have another question can I delete the play, refresh or seek button? I tried to delete the play button function once but the displays and the player itself got a lot of errors.

**Comment by terrill** [comment]
@Gymboree no, the player depends on each of its buttons being present. There's some thought of making that user-customizable within Preferences, but that's another issue.

**Comment by toomanynates** [comment]
How might I make the playback controls larger when viewed on a phone? When I view them on a phone, they're very tiny.
