### ISSUE TITLE
Google Analytics - Onprogress

### ISSUE THREAD

**Issue by webguyzz** [ableplayer/ableplayer#280]
@terrill Hi, we are trying to use GA tags to track the player events: play, stop, pause, abort and completion rate. We have successfully used onplay, onpause, onabort, onended. We assume we can use onprogress to determine the completion rate (at least 25%/50%/75%). But, we haven't figured out the way to use onprogress. Please assist. Thanks!

**Comment by terrill** [comment]
The **progress** event actually won't help determine completion rate - that has more to do with the browser's progress in downloading the media file. To monitor users' completion rate, you'll need to do some calculations triggered by the **timeupdate** event. 

I added a media event log to the native player demo in c2f190a253f86dcf5ae0a13417992d027405f723 - see other1.html in the develop branch for example code, which includes tracking of percent completed and logging when the user hits specified targets.   

This works independently of Able Player and should continue to work if Able Player is used. However, I'm also planning to add Google Analytics tracking functionality within Able Player soon, so stay tuned for that in a forthcoming commit.
