### ISSUE TITLE
JSON Timestamp Support insted of WEBVTT

### ISSUE THREAD

**Issue by jaydev1997** [ableplayer/ableplayer#281]
I tried to insert json timestamp file, but console returns error

```Invalid WebVTT file: transcript.json
Line: 1, Column: 1
Invalid signature.
AblePlayer.parseWebVTT @ ableplayer.js:2068
```

Please Help me, i want to use json insted of vtt.

**Comment by terrill** [comment]
Sorry, AblePlayer only supports WebVTT tracks, which is consistent with the HTML5 spec.
