### ISSUE TITLE
How do I get Able Player to automatically generate transcripts?

### ISSUE THREAD

**Issue by c0brarules** [ableplayer/ableplayer#282]
I'm not sure if I am perhaps just not reading this correctly but on the [https://ableplayer.github.io/ableplayer/](url) page it states:

> "To manually code the transcript, one simple strategy is to first allow Able Player to automatically generate a transcript. Then copy and paste its content as a starting point."

Am I correct that this means I can take video file that has now transcript and have Able Player somehow create a transcript of the video for me, much like the same way that YouTube does with it's auto video transcripts?

How do I perform this process? I can't seem to find an example that shows this feature.

Thanks.

**Comment by terrill** [comment]
Good question @c0brarules . Able Player automatically creates transcripts from the VTT files you provide. So, you need to provide at least a caption file, supplemented if needed with a chapters and description, all in VTT format. Then Able Player generates a transcript and displays it in its own transcript window, which can be toggled on and off with the transcript button.  

The content you're referencing in the documentation refers to copying the source code from that automatically-generated transcript and pasting it directly into the web page. Advantages of doing it this way are: 

1. AblePlayer doesn't have to re-assemble the transcript each time the page is loaded, thereby improving performance. 
2. It gives you added flexibility over the transcript structure. You can add paragraphs, lists, etc., or correct any problems that emerged with the automatic transcript. 
    
Make sense?

**Comment by c0brarules** [comment]
Hi @terrill 

Thanks very much for the quick and detailed response, I appreciate that.

I think I see what you are saying. I guess I should have thought of that after going back to the [https://ableplayer.github.io/ableplayer/ ](https://ableplayer.github.io/ableplayer/) page and reading the first line in that section.

> **Transcript**
Able Player can automatically generate an accessible interactive transcript from the chapters, captions, and descriptions tracks.

I figured it was too good to be true in having Able Player automatically making a transcript straight from the video like YouTube does, but still a very powerful tool. I look forward to using it.
:-)

If I have another question, should I continue this thread or create a new thread for each question?

**Comment by terrill** [comment]
@c0brarules a new thread for each unique question would be best, so the title of the issue matches the content. I'm closing this one now.
