### ISSUE TITLE
Video get cropped from top and bottom when full-screen with Chrome

### ISSUE THREAD

**Issue by webguyzz** [ableplayer/ableplayer#286]
For Chrome users, if using the full-screen, the video gets cropped off from the top AND bottom.  I found out, if I then used Ctrl and +/- to adjust the Zoom for the Chrome, the issue can be resolved. The quick fix is NOT ideal.

However, such issue only exist on Chrome. Please investigate. 

e.g. http://ableplayer.github.io/ableplayer/demos/video1.html or our site
http://hadley.edu/PlayVideo.asp?vid=114

Thanks!

**Comment by terrill** [comment]
Duplicate. See #285

**Comment by terrill** [comment]
@webguyzz I can replicate this in Chrome 58 and 59 on Windows 10.  As you noted, it doesn't appear to be a problem in any other browsers, including Chrome 59 on Mac (I tested on Mac OS Sierra). 

Just to be sure we're observing the same problem, I wouldn't describe it as "cropping". The entire video is visible. It's just not positioned optimally. It occupies slightly less than full screen, and there are visible light gray margins appearing above and below the video. 

I'll investigate this,  but it will have to wait a bit. There are some other issues ahead of it in the queue.

**Comment by webguyzz** [comment]
Yes, video was not fully displayed in latest Chrome.
Thanks.

Zhiyang Zheng
Senior Web Developer
Hadley Institute for the Blind and Visually Impaired
700 Elm Street, Winnetka IL 60093
847-784-2710 (ph)
847-386-5443 (fax)
