### ISSUE TITLE
Playing an 'unlisted' or 'private' YouTube video?

### ISSUE THREAD

**Issue by dchoi87** [ableplayer/ableplayer#293]
Hello,

Is there a way to play **unlisted** Youtube videos? I've set up my youtube data API key properly and have successfully played my videos with the privacy set to **public**, but once I change it **unlisted** or **private**, I am unable to play it. Any help would be appreciated! Thanks!

**Comment by terrill** [comment]
@dchoi87 Able Player can play unlisted videos, but not private ones.  I just confirmed that it's still working with unlisted videos. Are you sure the YouTube ID id of your unlisted video is correct in the data-youtube-id parameter?

**Comment by dchoi87** [comment]
Thank you for your response. I double checked and the YouTube ID of the unlisted video is the same as what's in data-youtube-id.

It appears that if you're not using the youtube api key, then you are able to play unlisted videos. But, when using the youtube api (we're trying to pull in captions from the Youtube video), I am unable to play unlisted videos. Basically, getting the following 404 error:

![youtube-api-404](https://user-images.githubusercontent.com/20117685/30605956-e80ba1c4-9d24-11e7-9277-85acf7271207.png)

The video is ours, and the youtube api key is tied to the account the video is on.

Thanks for the help!

**Comment by terrill** [comment]
Hmmm. Interesting. Changing this to a bug.

**Comment by terrill** [comment]
With [Able Player 4.4](https://github.com/ableplayer/ableplayer/releases/tag/v4.4), we had to make changes to how we're handling YouTube videos. I'm closing this issue with an update on the current status, confirmed with extensive testing:   

- No YouTube API key is required. 
- Able Player **does not** support **private** videos. 
- Able Player **does** support **unlisted** and **public** videos.
