### ISSUE TITLE
Full screen positioning bug in Safari

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#302]
Observed in Safari 11 (MacOS Sierra 10.12.6): The entire UI in full screen mode is shifted downward slightly, with empty white space at the top. The status bar is entirely off-screen, but all other controls are visible. (screen shot attached)

This was originally noted in https://github.com/w3c/wai-showcase-examples/issues/308#issuecomment-337572533

![ableplayer-fullscreen-safari-bug](https://user-images.githubusercontent.com/912874/31727195-d7fd154a-b3dd-11e7-9044-bb4942e0f88e.png)

**Comment by yatil** [comment]
It looks like the `margin: 1em 0;` on the `.able` element is causing the downshift. But even without it, I cannot see all controls here: 
<img width="1680" alt="screen shot showing the controls bar cut off" src="https://user-images.githubusercontent.com/58862/31728384-7891e53c-b42c-11e7-8f6f-f6b72f9b724a.png">

It only shows if I set the `.able-vidcap-container` height to something around 900px in the inspector.

**Comment by jmcglone** [comment]
This looks to be an ongoing issue in Safari. However I think with Safari version changes over the years the bug has evolved. For example:

**Safari 12**
the white bars appear in the top and bottom of full-screen mode
controls are not visible
captions display

![Screen Shot 2020-12-01 at 4 38 05 PM](https://user-images.githubusercontent.com/1686111/100800006-f5de7b00-33f3-11eb-9094-2cac8f40e3a8.png)

**Safari 13**
the white bars still appear in the top and bottom of full-screen mode
controls are fully visible
captions are partially cutoff

![Screen Shot 2020-12-01 at 4 35 20 PM](https://user-images.githubusercontent.com/1686111/100800072-0ee72c00-33f4-11eb-8265-10bedad74dce.png)

**Safari 14**
the white bars still appear in the top and bottom of full-screen mode
controls are fully visible
captions are not displaying

![Screen Shot 2020-12-01 at 4 30 41 PM](https://user-images.githubusercontent.com/1686111/100800118-20303880-33f4-11eb-946a-d05db9281287.png)

Safari 13 and 12 were tested with LambdaTest (real-time browser testing) while Safari 14 was tested locally on a MacBook Pro running Catalina 10.15.6 looking at an implementation of AblePlayer 4.3 (with a few customizations) at [this academic journal](https://quod.lib.umich.edu/d/dsdj/15499139.0005.003/--2006-protest-from-the-black-deaf-side?rgn=main;view=fulltext).

**Comment by terrill** [comment]
This should be fixed now on the develop branch, tested in multiple versions of Safari on multiple computers running multiple versions of MacOS, with both "legacy" and "2022" themes.  I'm closing this issue for now, but if you continue to experience problems with full screen mode in Safari, please report them here with as much detail as possible.
