### ISSUE TITLE
Additional buttons to toggle captions and audio descriptions

### ISSUE THREAD

**Issue by suchpower** [ableplayer/ableplayer#304]
Is it possible to create a button elsewhere on a page (outside of the player itself) and trigger the toggling of the captions and/or audio descriptions in the player?

**Comment by terrill** [comment]
@suchpower have a look at our [Video Demo 13](https://github.com/ableplayer/ableplayer/blob/develop/demos/video13.html) - that provides an example that shows how to setup Able Player so you can operate it with external controls.
