### ISSUE TITLE
Support for "playsinline" attribute on videos

### ISSUE THREAD

**Issue by ethanbutler** [ableplayer/ableplayer#307]
Hi! I'm the developer on Duke's [Rutherfurd Living History](http://livinghistory.sanford.duke.edu/) project, which uses Able Player. One of the features we're exploring is support for playing inline videos on iOS, which is [supported as of 2016](https://webkit.org/blog/6784/new-video-policies-for-ios/).

I imagine this would already work for self-hosted video since the `playsinline` attribute can be added directly to the `video` element, but for YouTube video, a particular query has to be [appended to the src attribute of the `iframe`](https://stackoverflow.com/questions/33367473/display-youtube-video-inline-on-ios-devices). Because of how Able Player's API for YouTube embeds works (users specify an ID, not a URL) I'm imagining that I'll need to fork the project and add support for this.

I wanted to see if the project maintainers would be interested in receiving a pull request for this behavior, and if so, the best way for this API to look.

(I would imagine the API for this opt-in behavior would look like adding an attribute like `data-youtube-playsinline` to the `video` element.)

Thanks!

**Comment by terrill** [comment]
Thanks for bringing this up @ethanbutler. I too have been looking at **playsinline**.  I'm going to be committing quite a few updates over the next few weeks, including several that directly impact the YouTube player. Do you mind waiting?  I'll try to address this issues among the updates I'm making, but if I don't get to it, I'd be more open to a pull request on  the develop branch after my current burst of activity.

**Comment by ethanbutler** [comment]
Totally understood! Just a headsup – in order to get this to work, all I had to do add `playsinline: 1` to arguments option passed to the `YT.Player` constructor in scripts/youtube.js.

**Comment by terrill** [comment]
This has been added in 08c856881b1045c995e7b724653835ea7d713a79 

Simply add the **playsinline** attribute to the `<video>` element. If you're using Able Player to play YouTube videos, Able Player will repurpose that attribute and pass playsinline:1 to YT.Player.  

Thanks for your help with this @ethanbutler !
