### ISSUE TITLE
Make "animals" the default for speed icons

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#308]
I'm 95% sure I want to do this, but thought I'd create this issue to document my reason for doing so, and to offer the community a chance to weigh in.
 
Here's the player with the default "Faster" and "Slower" icons (data-speed-icons="arrows"): 

<img width="520" alt="screen shot of player, with up arrow icon representing faster and down arrow icon representing slower" src="https://user-images.githubusercontent.com/912874/36868740-28bcb7d6-1d4e-11e8-9713-d57cb2893e24.png">

And here's the player with data-speed-icons="animals": 

<img width="509" alt="screen shot of player, with rabbit icon representing faster and turtle icon representing slower" src="https://user-images.githubusercontent.com/912874/36868739-28989568-1d4e-11e8-8a46-be759139005b.png">

Based on informal polls of numerous audiences at presentations (designers and developers) and interviews and focus groups with users (at CSUN 2017), there seems to be a very strong preference for animals. Here's some justification: 

- The purpose of the current icons (arrows) is unclear. 
- The current design has too many arrows already. Therefore the arrows just add confusion (arrows pointing in all directions).    
- The turtle and rabbit are universally recognized as representing "slow" and "fast". This is based on interviews with people from all continents except Antarctica.
- The turtle and rabbit are fun and cool. 

The last item in the above list is actually the only reason I'm hesitating. Generally I don't think "fun and cool" is good justification for making a web design choice. Also, "fun and cool" are subjective, and some website owners are sure to disagree. 

That said, authors can still override the default with the **data-speed-icons** attribute.

**Comment by Egyrs** [comment]
+1 for the turtle and the rabit 👍 
There are another raison: They can be useful to facilitate the understanding to deaf people and with some cognitive deficiencies, the arrows are more abstract.

**Comment by terrill** [comment]
Thanks @Egyrs for the additional reason. I went ahead and made this change in 6dd170928cf6e3c41e531b838c6174eb7191388b
