### ISSUE TITLE
Hard-code/override player heading level

### ISSUE THREAD

**Issue by rubinsztajn** [ableplayer/ableplayer#309]
Is there a way to hard-code the heading level for the player? It looks like it tries to guess the next heading level based on context but that ends up creating inconsistent heading levels across the site. It would be great to be able to override this behavior and tell all players to be an `<h2>`, for example.

**Comment by terrill** [comment]
There's no way to override that functionality currently, but I can add that feature easily enough. I'll do so soon, probably this week.

**Comment by terrill** [comment]
This has been addressed in 49c278e67fa09eaf93d4300928837b0520f4ae28

You can manually override the default heading level with the **data-heading-level** attribute. Valid values are 1-6. The value you enter is the heading level that will be assigned to the off-screen "Media Player" heading that's injected immediately prior to the media player. You can also enter a value of "0", which means "no heading". This should be used only if the web page already includes a heading immediately prior to the media player.
