### ISSUE TITLE
Faster/Slower not working on IE

### ISSUE THREAD

**Issue by kwills34** [ableplayer/ableplayer#311]
Hello, I'm using IE browser, version 11.0.96, and the faster (hare) and slower (turtle) buttons are not working to change the video speed.

p.s. this is just a small hitch in the scope of all the good and accessible functionality you bring! Thank you for creating and maintaining this great player.

**Comment by terrill** [comment]
@kwills34 I'm not able to replicate this in IE 11.248.  In my tests, both buttons work fine.

**Comment by terrill** [comment]
Closing this for now. Feel free to Reopen it if you continue to observe the problem.
