### ISSUE TITLE
new AblePlayer() does not work when passing in a jQuery selector

### ISSUE THREAD

**Issue by erikTmay** [ableplayer/ableplayer#324]
I get the following error in my browser dev console:

ableplayer.js:192 Uncaught (in promise) TypeError: media.find is not a function
    at new window.AblePlayer (ableplayer.js:192)

looks like media just needs to be wrapped in jQuery on line 192

**Comment by terrill** [comment]
Good catch @erikTmay ! This should now be fixed in 4ca9d808e1097dfd156392ecaaf60d96d53bdf6a
