### ISSUE TITLE
Captions highlighting not working in Chrome 

### ISSUE THREAD

**Issue by jamiepratt** [ableplayer/ableplayer#325]
For example in the demo demos/audio4.html I can click on part of the transcript to move to that part of the song. But the transcript is not highlighted as the song is sung. Also the autoscroll is not working.

The highlighting works fine in Safari and Firefox.

Chrome 66.0.3359.181 (Official Build) (64-bit) on a Mac

**Comment by terrill** [comment]
@jamiepratt I'm not able to replicate this. Seems to be working fine for me in the same version of Chrome, also on a Mac. Do you get any errors in the dev console?

**Comment by jamiepratt** [comment]
Does it work for you on  my web site : http://jamiep.org/dharmapunx/demos/audio4.html

There are no errors in the dev console.

Here's a screen capture : https://youtu.be/DUeSL9v2dPc

**Comment by jamiepratt** [comment]
I added debug data attr to the audio for http://jamiep.org/dharmapunx/demos/audio4.html

Also I added some console.log statements in the tracking code but they're not reached in chrome.

https://github.com/ableplayer/ableplayer/compare/master...jamiepratt:chrome_tracking_debug?expand=1

**Comment by jamiepratt** [comment]
Seems like this could be a intermittent bug! Mostly transcript highlighting has not worked for me in Chrome. BUT occasionally it does for some time and then stops working again. :-(

**Comment by jamiepratt** [comment]
I'm getting the following output in Safari 

[Log] User agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15 (ableplayer.js, line 6972)
[Log] Vendor: Apple Computer, Inc. (ableplayer.js, line 6973)
[Log] Browser: Safari (ableplayer.js, line 6974)
[Log] Version: 11.1 (ableplayer.js, line 6975)
[Log] OS: Mac/iOS (ableplayer.js, line 6976)
[Log] User agent: mozilla/5.0 (macintosh; intel mac os x 10_13_4) applewebkit/605.1.15 (khtml, like gecko) version/11.1 safari/605.1.15 (ableplayer.js, line 6983)
[Log] User agent: mozilla/5.0 (macintosh; intel mac os x 10_13_4) applewebkit/605.1.15 (khtml, like gecko) version/11.1 safari/605.1.15 (ableplayer.js, line 6983)
[Log] User agent: mozilla/5.0 (macintosh; intel mac os x 10_13_4) applewebkit/605.1.15 (khtml, like gecko) version/11.1 safari/605.1.15 (ableplayer.js, line 6983)
[Log] media volume change to 7 (volume-medium) (ableplayer.js, line 10613)
[Log] media play event (ableplayer.js, line 10586)
[Log] highlightTranscript called with time 0.143350618 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 0.394162999 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 0.6442906 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 0.895471498 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 1.145975711 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 1.396785089 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 1.647212918 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 1.898123947 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 2.148462062 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 2.399462076 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 2.649646809 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 2.90082386 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 3.151108348 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 3.402120607 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 3.652498752 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 3.903349401 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 4.153761778 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 4.404635251 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 4.655009125 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 4.906052019 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 5.156466964 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 5.407315512 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 5.657739424 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 5.908792383 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 6.159134874 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 6.410103981 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 6.66042682 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 6.911311602 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 7.161617206 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 7.412749096 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 7.662938561 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 7.914114589 (ableplayer.js, line 9626)
[Log] highlightTranscript called nothing highlighted. (ableplayer.js, line 9651)
[Log] highlightTranscript called with time 8.164474094 (ableplayer.js, line 9626)
[Log] highlightTranscript called highlighting. (ableplayer.js, line 9644)
[Log] highlightTranscript called with time 8.415342716 (ableplayer.js, line 9626)
[Log] highlightTranscript called highlighting. (ableplayer.js, line 9644)
[Log] highlightTranscript called with time 8.665767596 (ableplayer.js, line 9626)
[Log] highlightTranscript called highlighting. (ableplayer.js, line 9644)
.....

**Comment by jamiepratt** [comment]
But with Chrome this is all I get, after pressing play : 

User agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
ableplayer.js:6973 Vendor: Google Inc.
ableplayer.js:6974 Browser: Chrome
ableplayer.js:6975 Version: 67.0
ableplayer.js:6976 OS: Mac/iOS
ableplayer.js:6983 User agent: mozilla/5.0 (macintosh; intel mac os x 10_13_4) applewebkit/537.36 (khtml, like gecko) chrome/67.0.3396.79 safari/537.36
ableplayer.js:6983 User agent: mozilla/5.0 (macintosh; intel mac os x 10_13_4) applewebkit/537.36 (khtml, like gecko) chrome/67.0.3396.79 safari/537.36
ableplayer.js:6983 User agent: mozilla/5.0 (macintosh; intel mac os x 10_13_4) applewebkit/537.36 (khtml, like gecko) chrome/67.0.3396.79 safari/537.36
ableplayer.js:10613 media volume change to 7 (volume-medium)
ableplayer.js:10586 media play event

**Comment by jamiepratt** [comment]
It's working on Chrome on my Samsung Note 8

Google Chrome67.0.3396.81(Official Build) (32-bit)Revision64c9f2740c7d18e0afb35e98c01129be7db49850-refs/branch-heads/3396@{#762}OSAndroid 8.0.0; SM-N950F Build/R16NW

**Comment by jamiepratt** [comment]
In case it helps, more version info for my MacBook Chrome : 


Google Chrome | 67.0.3396.79 (Official Build) (64-bit)
-- | --
Revision | 161bdad7314804dc8c72f850396fcd696e8863e8-refs/branch-heads/3396@{#755}
OS | Mac OS X
JavaScript | V8 6.7.288.44

**Comment by terrill** [comment]
First, I encourage you to upgrade to the latest version of Able Player. Looks like you're running version 2.3.86, whereas the [latest stable release](https://github.com/ableplayer/ableplayer/releases) is 3.1.00.   

That said, I don't think that would fix the problem because it actually does work fine for me in Chrome/Mac on your website.  This suggests to me that the problem is unique to your Chrome instance, perhaps due to an extension?  Trying disabling all your Chrome extensions and see if the problem persists.  

A bit more thinking aloud: 
- In your logs for both Safari and Chrome, the media 'play' event is fired. 
- Your logs differ after that:  In Chrome, highlightTranscript() is not called. 
- The latter is called from the onMediaUpdateTime() and addSeekbarListeners() functions, so that's where I would focus my troubleshooting. In onMediaUpdateTime(), there are a few conditions that must be met in order for highlightTranscript() to be called. If those conditions aren't being met, why not? 

Also, this might be obvious, but are you sure highlighting is enabled in your user preferences within Chrome? (Preferences button > Transcript > "Highlight transcript as media plays" should be checked).

**Comment by jamiepratt** [comment]
Hi,

Thanks a lot for your response @terrill.

Seems although I'd thought I'd updated to the latest version of the able player, actually I'd only updated my local copy and not my remote copy. Only files that I was manually editing where getting updated on the remote machine.

The transcript is now working great on 3.1 and I tried in v2.3 and it worked great there too.

Thanks for your help and thanks for putting together this VERY cool project.

Jamie
