### ISSUE TITLE
All controls, buttons in one line

### ISSUE THREAD

**Issue by BonBonSlick** [ableplayer/ableplayer#327]
Tell me please the best way to move speed control buttons, from second able-left-controls to first able-left-controls where play button is. Because at the moment player is too big. We want it be compact and small.

 I have found the way to edit icons in builder.js. But functional still old, like ico has changed to what i need, but it increasing sound but not speed. And i have hide some buttons, with dispaly none, and now i am getting erros

```
Uncaught TypeError: Cannot read property 'show' of undefined
    at window.AblePlayer.AblePlayer.onClickPlayerButton (ableplayer.js:10344)
    at HTMLButtonElement.<anonymous> (ableplayer.js:10763)
    at HTMLButtonElement.dispatch (jquery.js:3)
    at HTMLButtonElement.q.handle (jquery.js:3)
```

Because these buttons hidden....

**Comment by terrill** [comment]
@BonBonSlick unfortunately Able Player wasn't really designed to be customizable in that way. See issue #305.
