### ISSUE TITLE
resetting cc track via Javascript fails?

### ISSUE THREAD

**Issue by bradleycbotkin** [ableplayer/ableplayer#328]
I'm trying to use my own playlist to refresh the AblePlayer with new clip source and CC track.  When there's a video element with source and track elements in the *static* page, all is well, CC button appears and operates. And when you remove the source element and recreate it (to perhaps play a different clip) via javascript, AblePlayer correctly picks up the new video source.  But if the track elements are removed and then created during that same process, the CC track is not refreshed.  What's the correct way via Javascript to reset the video element html to play a new set of source + ccfile?

**Comment by terrill** [comment]
@bradleycbotkin playlist support is not currently very robust. I actually added its current capability when Able Player was just an audio player, so all it does is swap the media source, not all the track sources that accompany it.  Fixing this is a high priority issue: #157
