### ISSUE TITLE
iPhone iPad jump back when text is selected

### ISSUE THREAD

**Issue by KimPatch** [ableplayer/ableplayer#332]
On this Able Player [Demo](https://ableplayer.github.io/ableplayer/demos/youtube.html) page, use an iPhone or iPad to to navigate the video – click on a sentence, the sentence is highlighted, the highlight flickers off then on again, and the video advances to that place in the transcript. 

This works well except – occasionally  – the highlight briefly jumps back to the sentence before and then forward again to the sentence you want. This doesn't happen on a full size computer or iPad Pro, just iPad and iPhone. 

This highlight jump back to the sentence before happens occasionally on the Able Player site, but it happens most of the time on The Rutherfurd Living History site, e.g. https://ableplayer.github.io/ableplayer/demos/youtube.html on iPad, iPhone and iPad Pro, but not on a full  size computer.

Any idea what is causing this or what we can do to make it stop?

**Comment by terrill** [comment]
@KimPatch Sorry for the slow response. I can confirm that I'm seeing this too, and it's not just YouTube videos. I'm seeing it on the other video demos as well.

**Comment by terrill** [comment]
I'm no longer observing this issue in Able Player version 4.x, iOS version 12.4.1 (tested on both iPhone and iPad, using the current 4.0 demo pages). Assuming it's no longer an issue, I'm closing this ticket. Feel free to reopen and provide detail it if you continue to observe symptoms with the latest version of Able Player.
