### ISSUE TITLE
Enable Fixed Seek Interval

### ISSUE THREAD

**Issue by df0ecc** [ableplayer/ableplayer#335]
Hi, thank you for your nice player. I am attempting to enable the 'fixed seek interval'.

`        }
        if (void 0 !== a(b).data("allow-fullscreen") && a(b).data("allow-fullscreen") === !1 ? this.allowFullScreen = !1 : this.allowFullScreen = !0,
        this.defaultSeekInterval = 10,
        this.useFixedSeekInterval = !1,
        void 0 !== a(b).data("seek-interval") && "" !== a(b).data("seek-interval")) {
            var f = a(b).data("seek-interval");
            /^[1-9][0-9]*$/.test(f) && (this.seekInterval = f,
            this.useFixedSeekInterval = !0)
        }`

I switch to !0 on the first instance of 'this.useFixedSeekInterval' and seek stops working completely. Also, I tried playing around with the numbers on the following lines, but it doesn't seem to have any effect except when I change the value of duration/steps calculation ('a / 10').

`  }
    ,
    AblePlayer.prototype.setSeekInterval = function() {
        var a;
        return this.seekInterval = this.defaultSeekInterval,
        a = this.useChapterTimes ? this.chapterDuration : this.getDuration(),
        "undefined" == typeof a || 1 > a ? void (this.seekIntervalCalculated = !1) : (20 >= a ? this.seekInterval = 5 : 30 >= a ? this.seekInterval = 6 : 40 >= a ? this.seekInterval = 8 : 100 >= a ? this.seekInterval = 10 : this.seekInterval = a / 10,
        void (this.seekIntervalCalculated = !0))
    }`

Am I missing something? Thanks for any help, please bear with me I'm not a coder.

**Comment by terrill** [comment]
@df0ecc I'm not clear on what you're trying to accomplish. 
If you just want to enable a fixed seek interval, you don't need to edit the source code. Just add a `data-seek-interval` attribute to the `<video>` element. The value of the attribute should be the number of seconds you'd like for your interval. Does that help?

**Comment by df0ecc** [comment]
Yes it does. I was way off, thanks.
