### ISSUE TITLE
Create a more robust Search demo

### ISSUE THREAD

**Issue by troyfmay** [ableplayer/ableplayer#346]
Hi Able Player devs!

Can you help me to understand how to add a Search Caption bar to my transcript area?

I have been referencing this page:

https://ableplayer.github.io/ableplayer/demos/video9.html

However, it has no search box which allows me to type in a search value. Can you guys fix that page so instead of the hypothetical result example, it allows me to search the caption in real-time myself?

**Comment by terrill** [comment]
@troyfmay to add video search you would just need to add a search form to your web page, then when that gets submitted the search terms could be parsed and added to the **data-search** attribute on the `<video>` tag (each search term separated by a space). 

The example page is just intended to provide a simple demo of the Able Player markup that could be used for building a more robust video search application. It's essentially just there to inspire you to build something, not to provide an actual functional application.  If we add a search form to the example page, we'd have to add validation, security checks, error handling, etc. which is more work than we were wanting to put into this simple example.

**Comment by troyfmay** [comment]
Thanks for the quick response! I do not know how to create a search form that will parse the typed input into the data-search attribute.

Please help, Terrill.

**Comment by troyfmay** [comment]
Thanks for the quick response! I do not know how to create a search form that will parse the typed input into the data-search attribute.

I have been able to procure some simple code I discovered at another site that does exactly what I need. 

https://testdrive-archive.azurewebsites.net/Graphics/VideoCaptions/

It does not employ any of the special functions you mentioned in your post. It is three JavaScript functions and about 15 odd lines of HTML. 

It just lets a person type a search value in a box, then locates all cues that text appears, and displays the lines consecutively in a handy box.

The problem is when I attempt to make this bit work with the Able Player, there is a conflict. Either the Able player commands the video tag or the search box does.   

To try and understand why the conflict was happening, I peeked at the javascript for your player. It appears to have a considerable amount of search functionality already written for it. Particularly, the function I need(in bold). 

// search VTT file for all instances of searchTerms
    **// Currently just supports search terms separated with one or more spaces**

    // TODO: Add support for more robust search syntax:
    // Search terms wrapped in quotation marks ("") must occur exactly as they appear in the quotes
    // Search terms with an attached minus sign (e.g., -term) are to be excluded from results
    // Boolean AND/OR operators
    // ALSO: Add localization support

It seems to only require an interface to get a good search form working for your player, sir. I wish I knew how to fix that up, myself. If I could, I would be trying to provide it to you to post for others who I am sure can benefit from its example.

Please help, Terrill.

**Comment by terrill** [comment]
@troyfmay that's a pretty cool example - thanks for sharing. 
I appreciate that video search offers a compelling use case for accessible video, and will add building a more robust example to my todo list. To that end, I'm renaming this issue and flagging it as a feature request. It's competing with lots of other issues though (96 issues currently in the queue), so I can't guarantee a speedy completion time (I'll do my best!)

**Comment by troyfmay** [comment]
Cool! That sounds great, Terrill! I am going keep working on adding a basic transcript/caption search, too. I am sure you are a far rung better developer than me. But if I get there first, I will be sure to share my results with you here at your GH. 

Thanks again!

PS: I have been using this player on and off for over a year now--not sure what of the 96 bugs it has, but I have yet to find any. Really great HTML5 community contribution, sir! :)

**Comment by terrill** [comment]
@troyfmay I finally got around to updating the search demo in ee5cdf2d4f79cc419aa21f120ce03b2061202556 

There are two demos now (in the develop branch), one describing and showing how search could work in a server-side search application; and a second one that shows a fully functional client-side search application.  Sorry this took so long.

**Comment by troyfmay** [comment]
Thanks for the info, Terrill. All this sequestered lockdown business has me finally getting to those back burner projects as well. Best of luck for yours to pay off, sir.

Troy May

On Apr 3, 2020, at 4:57 PM, Terrill Thompson <notifications@github.com> wrote:

﻿
This email is not from Hexagon’s Office 365 instance. Please be careful while clicking links, opening attachments, or replying to this email.


@troyfmay<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftroyfmay&data=02%7C01%7C%7Ce5d96d786a424652f03308d7d819f064%7C1b16ab3eb8f64fe39f3e2db7fe549f6a%7C0%7C0%7C637215478228750441&sdata=QRxHKw1YbGMk1PudKqRoMODWGUQqfyv1vgfDxfN46vc%3D&reserved=0> I finally got around to updating the search demo in ee5cdf2<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fableplayer%2Fableplayer%2Fcommit%2Fee5cdf2d4f79cc419aa21f120ce03b2061202556&data=02%7C01%7C%7Ce5d96d786a424652f03308d7d819f064%7C1b16ab3eb8f64fe39f3e2db7fe549f6a%7C0%7C0%7C637215478228750441&sdata=pV97YyhDNJGui4NYJir9N02uIgDfZPwessmg%2Fu030ag%3D&reserved=0>

There are two demos now (in the develop branch), one describing and showing how search could work in a server-side search application; and a second one that shows a fully functional client-side search application. Sorry this took so long.
