### ISSUE TITLE
Transcript scrollbar jumps around

### ISSUE THREAD

**Issue by daveywb** [ableplayer/ableplayer#351]
On longer transcripts, when the highlighted text gets to about half way, the able-transcript div starts jumping up and down.

I'm using Windows 10 and this behaviour is happening on Chrome and Firefox

Any ideas why this could be happening?

Thanks!

David

**Comment by terrill** [comment]
@daveywb a few questions: 

1. Do you have a live example? 
2. Which version of Able Player are you using? 
3. Is the "Auto scroll" checkbox checked? 
4. Do you experience the problem with [this 10-minute video](https://www.washington.edu/doit/videos/index.php?vid=89)?

**Comment by terrill** [comment]
I'm unable to replicate this in either Chrome or Firefox in Windows 10, so I'm closing the issue. 
My first hunch is that maybe there was a validation error in your WebVTT file(s). 

If anyone else experiences this, feel free to re-open the issue, and provide as much detail as possible.
