### ISSUE TITLE
Transcript file in audio Playlist

### ISSUE THREAD

**Issue by haidar1000** [ableplayer/ableplayer#352]
how active Transcript files for each mp3 file in audio Playlist?
thanks

**Comment by terrill** [comment]
@haidar1000 that isn't supported yet, but adding support is a high priority: 
https://github.com/ableplayer/ableplayer/issues/157

**Comment by terrill** [comment]
All items in an audio playlist can now have captions as of c0d291c70fd5b8be5879c6fef362407c699c17c3
