### ISSUE TITLE
NL not in supported languages

### ISSUE THREAD

**Issue by yatil** [ableplayer/ableplayer#355]
https://github.com/ableplayer/ableplayer/blob/d0a7ce62b149361628c1a41b0759798cbba2c33e/scripts/translation.js#L4

Have those updates happen, can we help to make them work?

(Related: https://github.com/w3c/wai-video-standards-and-benefits/issues/33)

**Comment by terrill** [comment]
The Dutch translation of Able Player needs to be updated. We added some new language a while ago that hasn't been translated yet. If someone would be willing to translate the content that's still in English in the Dutch translation file (translations/nl.js), then either send me the file or issue a pull request, we can get that working again. Thanks!
