### ISSUE TITLE
Some attributes not working with youtube video

### ISSUE THREAD

**Issue by DavidGuijarro** [ableplayer/ableplayer#361]
Hi, I've added data-transcript-div="transcript", data-captions-position="overlay" and data-hide-controls="false" on a video tag with a youtube video and doesn't work. The player shows buttons, the position of the captions is bellow and the transcript appears in a popup. Are these features implemented for youtube video too?

**Comment by terrill** [comment]
@DavidGuijarro thanks for reporting these issues. 

The YouTube transcript bugs (related to **data-transcript-div** and **data-hide-controls**) are now fixed as of dbd0894aad70863fca4d2cc9c677c99b1589816a

The other attributes you mentioned seem to be working as expected: 

- **data-captions-position="overlay"** allows the author/developer to set a default position for the captions, but the user's preference (as defined in their Preferences > Captions dialog) takes precedence. So, if you declare "overlay" as the default, and the user has their preference set to "below", the user will see captions below. The only users who will see captions as an overlay are those visiting your site for the first time (or with cookies disabled). To test this, visit your site in a private/incognito window. 
- **data-hide-controls="false"** is the default setting, so you actually don't even need to include that attribute. If you include data-hide-controls (by itself, with no value) or data-hide-controls="true", the player controls will fade out **after** the user initiates playback. If you omit data-hide-controls and have no player controls, that probably means the player is failing to fully initiate, which is entirely separate problem. If that's the case, please open a new issue and provide as detail as possible.
