### ISSUE TITLE
Can't Unpause Playlist

### ISSUE THREAD

**Issue by givepraise** [ableplayer/ableplayer#369]
https://ableplayer.github.io/ableplayer/demos/audio3.html
Noticed this with latest version. When you press pause on the playlist you are unable to start again unless you hit Restart button. Occurring on Firefox 68 & Chrome 75 Android.

**Comment by terrill** [comment]
@givepraise this was an issue in the v4.0 release, but it's been fixed in the develop version, as of d541fe372ffd13f6b268c38241cee8dd7aed4412. 

I'm fixing a few other issues too before releasing a new version (should be soon though).
