### ISSUE TITLE
Preload of Content shows incorrect time

### ISSUE THREAD

**Issue by givepraise** [ableplayer/ableplayer#370]
https://ableplayer.github.io/ableplayer/demos/audio1.html
When a player is pulled up the time is initially shown as '1:40'. Once the play button is press the correct time is displayed. This is a new behavior I notice with the latest version, occurring on Firefox 68 & Chrome 75 Android.

**Comment by terrill** [comment]
@givepraise This was fixed in the develop version, as of 30503aac1130c9cb3a2272685e4814e4bb1924ea

The fix will be in the next release.
