### ISSUE TITLE
Unable to navigate with in preferences popup menu

### ISSUE THREAD

**Issue by nutanroy** [ableplayer/ableplayer#372]
Unable to move up/down using keyboard arrow-keys under preferences option

**Comment by terrill** [comment]
@nutanroy I'm unable to replicate this. Which browser and operating system?  Are you using any assistive technology? Thanks for clarifying.

**Comment by nutanroy** [comment]
Greetings all,

Thank you for reverting back
In the new version of ableplayer, keyboard navigation keys are not working
(preferences menu),
whereas, in the old version of ableplayer, we are able to navigation is
working fine (preferences menu)

I am attaching the code and screenshots for the same.
Kindly, check it once and provide your suggestions to go with it.

Note : For your reference, I integrated ableplayer with the node sample
application.

 AblePlayerDemo.zip
<https://drive.google.com/a/deque.com/file/d/145l3aGh_ptWXXs8wxicT5MyyOcfpamdO/view?usp=drive_web>
Thanks and Regards
Nutan Roy

**Comment by nutanroy** [comment]
<img width="923" alt="OldPlayer" src="https://user-images.githubusercontent.com/43461549/62528391-6904cb00-b85a-11e9-913c-0fba31b87018.png">
<img width="980" alt="NewPlayer" src="https://user-images.githubusercontent.com/43461549/62528393-699d6180-b85a-11e9-950f-9b73e62023be.png">

**Comment by terrill** [comment]
@nutanroy you're using jQuery 1.8.2. Try upgrading to 3.x. The latest version is 3.4.1; the latest version I've tested Able Player against is 3.2.1.

**Comment by nutanroy** [comment]
Getting **this.rootPath as undefined** while load ableplayer.js dynamically via javascript
Example : undefined/button-icons/
resulting in, the player icons are not showing up

**Comment by nutanroy** [comment]
added **data-root-path="..."** property to the &lt;video&gt; tag, still no luck
