### ISSUE TITLE
Unable to load able-player in react

### ISSUE THREAD

**Issue by JaiswalR-ELS-CT** [ableplayer/ableplayer#373]
I want to use able-player in my react-app

I have followed all the steps mentioned in the readme file
but not able to see able player instead getting normal html5 video on the screen.

Is there something I am missing

**Comment by terrill** [comment]
@JaiswalR-ELS-CT I'm closing this issue as it's related to #189.  I see you posted comments to that issue as well - that's the best place to continue this conversation.
