### ISSUE TITLE
preload="none" makes Firefox stop between audio playlist tracks

### ISSUE THREAD

**Issue by lardconcepts** [ableplayer/ableplayer#375]
preload="none" makes Firefox stop between audio playlist tracks
Chrome is OK.
Changing preload="auto" fixes it.

AblePlayer 4.0.0.8 (dev)
Firefox 68.0.1 (64-bit)
NVDA 2019.1.1

**Comment by terrill** [comment]
@lardconcepts that doesn't surprise me - that's how the `preload` attribute is supposed to work. The Able Player README file uses `preload="auto"` in the sample code, as do all the demo files.
