### ISSUE TITLE
Trigger Preferences dialog directly, rather than a popup menu, if only one item in Prefs menu

### ISSUE THREAD

**Issue by lardconcepts** [ableplayer/ableplayer#376]
As it is at the moment, with an audi player, you need to click preferences, then keyboard.
I understand that with more complex configurations, it would be necessary to select the preference you wanted, but could it be made so "if prefchoices=1 then just launch that preference".

AblePlayer 4.0.0.8 (dev)
Firefox 68.0.1 (64-bit)
Chrome 76.0.3809.87 (Official Build) beta (64-bit)
NVDA 2019.1.1

**Comment by terrill** [comment]
@lardconcepts that's a good idea. I'm changing the title of this issue and making it a feature request.

**Comment by terrill** [comment]
Fixed in 33321f414dd88c829205e6ea3afc9dfdbce129b9
