### ISSUE TITLE
Vimeo player timeline and captions

### ISSUE THREAD

**Issue by danielbonnells** [ableplayer/ableplayer#379]
The timeline and the captions aren't showing up for me with Vimeo. They don't work on the example either. I'm on Chrome for Mac. I am using a Pro account.

https://ableplayer.github.io/ableplayer/demos/vimeo.html

**Comment by terrill** [comment]
@danielbonnells this bug has been fixed on [the develop branch](https://github.com/ableplayer/ableplayer/tree/develop). It hasn't yet made it into a new official release (a few more bugs to fix first).
