### ISSUE TITLE
rootPath getting as undefined

### ISSUE THREAD

**Issue by nutanroy** [ableplayer/ableplayer#381]
Getting this.rootPath as undefined while load ableplayer.js dynamically via javascript
Example : undefined/button-icons/
resulting in, the player icons are not showing up

added data-root-path="..." property to the &lt;video&gt; tag, still no luck

**Comment by terrill** [comment]
@nutanroy do you have a public URL where I could see this in action?

**Comment by terrill** [comment]
Closing this issue for now. Feel free to reopen it if you have additional questions or comments.
