### ISSUE TITLE
Problematic Seekbar on Chrome Android

### ISSUE THREAD

**Issue by givepraise** [ableplayer/ableplayer#383]
Problems when clicking on the seekbar on Chrome 76 Android. It's behaving very buggy, will only allow me to seek part of the time and time appears as "NaN:NaN". Previous version has desirable behavior which is a cooperative seekbar.

Recreated on https://ableplayer.github.io/ableplayer/demos/audio1.html

**Comment by terrill** [comment]
Thanks for the bug report @givepraise !  This is now fixed in 3915ae4aa86d5ccdd8bdcd5b37fb8e3d83f13f22
