### ISSUE TITLE
Edge browser support

### ISSUE THREAD

**Issue by SteveALee** [ableplayer/ableplayer#386]
In the [Compatability section](https://github.com/ableplayer/ableplayer#compatibility) of the readme you don't explicitly mention Edge and might like to. 

It's a separate browser to IE (especially since the move to chromium) and is the Windows default so I suggest it is worth adding to the list.

**Comment by terrill** [comment]
Good catch @SteveALee . We've been testing with Edge, just neglected to add it to the documentation. This has been fixed in 279a98d5ea4c983cf127e0ff9e93e99d835c5b01
