### ISSUE TITLE
Problems with drupal and ableplayer playllist buttons

### ISSUE THREAD

**Issue by GERMANOCARELLA** [ableplayer/ableplayer#389]
Hi,
)'m having problems with ableplayer and drupal 7, when I attempt to use playlist feature.
I installed a module named ableplayer, that loads libraries.
This module adds a view for audio and video named AblePlayer, that works fine, if there is no playlist to be displayed.
In order to make a playlist I created a CodeField with Display Suite.
I used html from audio3.html example and php to create the playlist, that is embedded in audio player.
All works, except for list buttons, that load the song I select, but refresh the page and AblePlayer restart from beginning of PlayList. 
If I use, instead, "previous track" and "next track" buttons, it works fine. Only <button type="button">Title of songs</button> cause refresh of the page.
I tried to insert onclick="return (false);" as button attribute, but nothing changed.
I suspect this is a drupal issue, but I'm asking help on various platforms.
I tried to activate debug with data-debug attribute, but my screen reader is unable to read log messages in console.
Maybe I can control playlist with javascript instead of use built-in playlist feature?

**Comment by terrill** [comment]
@GERMANOCARELLA the Drupal module is maintained separately from Able Player core. It's best to report module-related issues via the [Able Player Drupal Project site](https://www.drupal.org/project/ableplayer).  That said, I don't think they're actively maintaining the Drupal 7 module, focusing all their efforts instead on Drupal 8.
