### ISSUE TITLE
Playlist volume does not stay the same when swapping between playlists and the volume button disappears if it was previously muted.

### ISSUE THREAD

**Issue by mlubick** [ableplayer/ableplayer#390]
How to recreate the bug:
1. If you look at demos/audio3.html 
2. Change the audio on the volume bar for the first item in the play list to mute
3. Click any other item on the play list.   
4. Notice that the volume button disappears. (NOTE: If you choose not muted then the volume still does not stay the same but the button will not disappear)

**Comment by terrill** [comment]
Good catch @mlubick ! This is now fixed in 2be636b38ea9b2ffb9aa70bc1a7e7bc0cbea38ad
