### ISSUE TITLE
Using Space bar to Pause/Play can Cause issues in multiple browsers with Playlist functionality

### ISSUE THREAD

**Issue by mlubick** [ableplayer/ableplayer#391]
If you look at the [play list example](https://ableplayer.github.io/ableplayer/demos/audio3.html).  

If you use spacebar to pause or play the audio the play button, while the focus of the page is outside of the audio player then the audio will stop working until the user selects the "Restart" button for the current track.  The issue will reappear sometimes even after the "Restart" button is selected.

I've notice this in Chrome for Mac and Windows and IE11.  It may also show in other browsers, but I've definitely seen it in these.

**Comment by mlubick** [comment]
While debugged I have noticed that the playing attribute of the AblePlayerInstace gets stuck as playing=true.  So it seems like it might be some kind of race condition.

**Comment by terrill** [comment]
@mlubick thanks for the tip about the playing attribute. That was a huge help.  This is now fixed in f34ae217e84cd04ee71746595c8248f7f1b8fb60
