### ISSUE TITLE
Transcript > Window options > Keyboard issues

### ISSUE THREAD

**Issue by sprungmarker** [ableplayer/ableplayer#392]
Example page:
https://ableplayer.github.io/ableplayer/demos/video1.html

It is not possible to use Transcript > Window options > i.e. Resize with keyboard. You can tab or use arrow to get to the option, but not active the option with keyboard (i.e. enter).

And you can only close with ESC the option window, with tab you cannot leave the menu.

Thx - btw a great player :)

**Comment by terrill** [comment]
Thanks @sprungmarker ! This has been fixed in 44ef90ed6b46701986507deadeb4811f1b04c223

**Comment by sprungmarker** [comment]
thx :)
