### ISSUE TITLE
Unable to load media files and .vtt files from remote location

### ISSUE THREAD

**Issue by nutanroy** [ableplayer/ableplayer#393]
While loading the files (.mp4, .vtt, etc.,) from remote location, able player unable to load and throwing CORS error

**Comment by terrill** [comment]
Hi @nutanroy this is a browser issue; Able Player is only providing the user interface. If the browser can play the video and show captions in a native HTML video element, Able Player should be able to do the same. However, if the browser can't, Able Player can't either. 

If you discover that you can play the remote videos and/or remote captions in a native HTML video element (without Able Player), but the same files fail in Able Player, please reopen this issue with more details (including a URL, if possible) and I'll look into it further. 

CORS errors do present a challenge. I find the [MDN page on CORS Errors](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) to be a helpful resource.
