### ISSUE TITLE
Bug - Autoscroll breaks with multiple players which have transcripts

### ISSUE THREAD

**Issue by JoshMoreno** [ableplayer/ableplayer#411]
The current jquery selectors are too broad and they match all players on the page. It seems like this was just looked over as most of the codebase is properly limiting selectors to the current instance's elements.

But for transcripts it's looking for elements anywhere which leads to unexpected results.
I'm going to test my pr right now and submit if it's working.

**Comment by terrill** [comment]
Fixed in f5b3736bdde56c81cfc64955bd06d4dccb8a396a
