### ISSUE TITLE
Adding custom buttons

### ISSUE THREAD

**Issue by cube-access-repo** [ableplayer/ableplayer#415]
Hello,

What is the fastest way to add custom buttons to the player

**Comment by terrill** [comment]
@cube-access-repo what do you mean by "add custom buttons"?  Do you want to change the appearance of existing buttons, or do you want to add entirely new buttons that provide new functionality?

**Comment by terrill** [comment]
The short answer to this is:  Custom buttons are not supported. 

That said, it's possible to replace the existing buttons, but it would be a significant undertaking. Note that all buttons exist in three formats:  SVG, font icons, and PNG (both black and white).  Which of these formats is used is determined programmatically based on browser support.
