### ISSUE TITLE
Are then any Javascript events, specifically "onTime()"?

### ISSUE THREAD

**Issue by gdpodesta** [ableplayer/ableplayer#416]
We depend heavily on this function, that is available with JWplayer.  Is such a function available with AblePlayer?

**Comment by terrill** [comment]
The equivalent to JWPlayer's "onTime" event in the HTML5 media API is "timeupdate". See the [Able Player API demo](https://ableplayer.github.io/ableplayer/demos/video13.html) for an example. That example includes event listeners for "playing" and "ended". You could add a similar event listener for "timeupdate".
