### ISSUE TITLE
Allow remote caption file

### ISSUE THREAD

**Issue by paulbohman** [ableplayer/ableplayer#419]
We have the need to load remote videos and captions from a cloud-based media server. We have been able to successfully load remote videos, but not remote captions. One of our programmers wrote some code to pull down the remote captions into a base64 text data format, which works in all browsers except for IE. I'm not convinced using a base64 data format is the best long term solution, as it seems kind of a brute-force work-around. If there is a way to alter the way the media player works across domains, to pull down videos and caption files, that would be enormously useful to us. 

Related issues:
https://github.com/ableplayer/ableplayer/issues/414
https://github.com/ableplayer/ableplayer/issues/360

**Comment by terrill** [comment]
@paulbohman I agree that this is a high priority (sorry it's taken so long to respond). However, I'm closing this issue as I think it's sufficiently addressed in #360. If you feel there's additional information needed in that other issue, feel free to post additional comments there.
