### ISSUE TITLE
Support for light theme for able-skin-2020

### ISSUE THREAD

**Issue by sacarney** [ableplayer/ableplayer#429]
A light theme would work better for our application. I could write a CSS file to override it by hand, but I want to make sure there isn't an option built in first. 

For the 2020 skin, I see that there's a class available in the css `able-black-controls` on the `able-controller` (which would get me half-way) but I can't see how to get that class into the HTML.

**Comment by terrill** [comment]
@sacarney sorry for the slow response.  Able Player uses either black controls or white controls, and does so intelligently based on the background-color of the **.able-controller** class.  It chooses either or black or white based on which of those two colors will result in the greatest contrast ratio.  

By default (in ableplayer.css), **.able-controller** has `background-color: #464646`, which is a dark color, therefore it uses white controls. You can change the background colors of the player using CSS, and if you change to a lighter color overall, Able Player will use black controls.  

If you need the controls to be a color other than black or white, that isn't currently supported.

**Comment by sacarney** [comment]
What a great feature! Thanks for the response. :)
