### ISSUE TITLE
Add aria-label to big Play Button

### ISSUE THREAD

**Issue by bzgaLindner** [ableplayer/ableplayer#438]
While the small play/pause button has correct aria-label, the big one (overlay on video itself) misses this label. 

This could be easily implemented by adding the following to /build/ableplayer.js (and ableplayer.min.js likewise, in latest commit bee2fa7):

```
...
3137                this.$bigPlayButton = $('<button>', {
3138		         'class': 'able-big-play-button icon-play',
3139		         'aria-hidden': true,
+ 3140                      'aria-label': this.tt.play, 
3141			'tabindex': -1
3142		});
...
```

Thanks and sorry for directly inserting without diff-file.

D. Lindner

**Comment by terrill** [comment]
@bzgaLindner the big play button has **aria-hidden="true"**, plus it's been removed from the tab order via **tabindex="-1"**. Given this, I don't think it needs a label. Screen readers should ignore it. Our thinking there is that screen reader users don't need two play buttons.  Feel free to disagree though. That may have been more true with the original controller configuration, when the play button was the first focusable element (therefore, the two play buttons were adjacent to each other). Now, with **data-skin="2020"** the seekbar separates them, so there's perhaps a greater case for exposing the big play button to everyone. I still think it's redundant though, therefore probably unnecessary.

**Comment by bzgaLindner** [comment]
Hi @terrill ,
thanks for clarifying this. You're right, for screen readers this should be suffficient. The missing aria-label was reported by an automatic web accessibility check. But if the button is "aria-hidden" anyway, it makes no sense to label it.
And by the way: thanks for this great player!
