### ISSUE TITLE
Consider changing position of preference modal

### ISSUE THREAD

**Issue by angelawolak** [ableplayer/ableplayer#448]
Currently the preference modals are set to appear positioned at `top: 5%`. This can be a little jarring if a page has a lot of content and uses a video near the bottom of the page, because you no longer see the video player itself when the preferences panel is open:

![current-behavior](https://user-images.githubusercontent.com/10479125/109873357-a0f11180-7c3b-11eb-94fe-a77018b1bbd0.gif)

Would it be possible to use `transform: translateY(calc(-50vh - 50%))` instead, to center the modal over the current viewport so that the player remains visible, like this:

![desired-behavior](https://user-images.githubusercontent.com/10479125/109873533-ddbd0880-7c3b-11eb-9033-37e6522e43a3.gif)

**Comment by terrill** [comment]
Great idea @angelawolak and thanks for including the recommended CSS! This has been implemented in 7981fe370ad355986e618121a259b2fdb0f155a2
