### ISSUE TITLE
Add a data-* attribute for the default state of pausing during description

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#449]
Pausing description had always been off by default, but was recently set to On by default on the develop branch.  This isn't a final decision - I'm hoping to make that based on data regarding the demand for extended description. 

In any case, website owners may have different needs for extended description based on the nature of their videos.  Therefore, we could add a **data-desc-pause-default** attribute (with options "on" or "off"), so website owners can override whatever the default settings ends up being.

**Comment by taija** [comment]
This would be fantastic! I'm currently implementing Able Player on our site for a series of videos that all use extended description. Right now we are using a 'swap' video that has the extended description baked in, but this causes sync issues with the captions if both captions and description are enabled at the same time (admittedly an edge case, but one that people are already complaining about).

**Comment by terrill** [comment]
@taija given your use case, you will be even more interested in #93 . Both of these features are on my short-term todo list.

**Comment by taija** [comment]
@terrill nice! Yes, in our case either would provide a clean way foreword. Many thanks, and a wave hello from across the lake at Bellevue College!

**Comment by terrill** [comment]
**data-desc-pause-default** has been added as of d05fd5b5ef605307059d273cc162a881f3f03d22
