### ISSUE TITLE
Any chance to get the full-screen working properly on Safari?

### ISSUE THREAD

**Issue by netcyberg** [ableplayer/ableplayer#450]
Can anyone please confirm if a full-screen suppose to be working on Safari?
I tested it on multiple devices and I couldn't get it work properly on any of it.
I tested it with a demo player page: https://ableplayer.github.io/ableplayer/demos/
Full screen is not working in Safari.

And secondly: any chance to get a video quality switcher?

Please confirm, thanks!

**Comment by terrill** [comment]
@netcyberg when you say full screen is "not working in Safari" I assume you mean the positioning is off, as reported in Issue #302. That's a known bug, which I hope to work on sometime soon.  If the problems you're experiencing are different from those described in that issue, please create a new issue and provide as much detail as possible about what exactly you're experiencing, and on which devices, including versions of operating systems. 

Regarding the feature to enable switching between video resolutions, that's on our roadmap, but I don't currently have an estimate as to when that will be addressed. You can track it via Issue #428.
