### ISSUE TITLE
Avoid eval() in ableplayer.js

### ISSUE THREAD

**Issue by bzgaLindner** [ableplayer/ableplayer#451]
Is it possible to replace eval() function in ableplayer.js in order to be usable in some restricted environments?

ableplayer's language selection uses:
`collapsedLang = thisObj.lang.replace('-','');
			thisObj.tt = eval(collapsedLang);`
(line 14388ff)

In some restricted environments the eval()function is not permitted by content security policy. I'm not a javascripter but I guess there is  a way to replace this function, isn't it?

Thanks,
Dominik

**Comment by terrill** [comment]
This has been addressed in 06ae5c884608dbdc62268a4a44614497b87d12ca
Thanks @bzgaLindner !
