### ISSUE TITLE
Having problem with the styles. Its overflowing over my navbars my cards. How to change its property?

### ISSUE THREAD

**Issue by cavinblake** [ableplayer/ableplayer#458]
Because of ableplayers styling property its changing the views of my pages..like flowing all over my navbars my cards all over my designs. How to solve it?

**Comment by terrill** [comment]
@cavinblake do you have a public URL where we can observe this?

**Comment by terrill** [comment]
I'm closing this for now. @cavinblake if it continues to be a problem, feel free to comment here and we can reopen.
