### ISSUE TITLE
Able Player does not work after closing and then opening the same pop-up

### ISSUE THREAD

**Issue by javz3** [ableplayer/ableplayer#460]
Hi, 

When on a page, and clicking on a link that opens a pop-up, the Able Player will work fine, however, after closing the pop-up and re-opening the same pop-op, the area for the Able Player is there but with no video or content, just a black area (where the video is supposed to be).

This following logic does not seem to work on pop-ups: https://ableplayer.github.io/ableplayer/demos/video11.html

Is there a way to destroy and recreate the able player? Or a way to hide the html and make it reappear so the above issue does not happen? It seems like the ableplayer.js is trying to recreate the player on the existing one.

Thanks

**Comment by terrill** [comment]
@javz3 are you still observing this problem in the new release ([version 4.5](https://github.com/ableplayer/ableplayer/releases/tag/v4.5))?  

In particular, I've created a new demo page [Player created dynamically](https://ableplayer.github.io/ableplayer/demos/external6.html) that might be relevant to what you're observing. 

Assuming your questions are addressed in that demo, I'm closing this issue. If you continue to experience problems though, feel free to post the details here and we can have a closer look.
