### ISSUE TITLE
Ableplayer js-cookie library conflicts with a newer version of js-cookie

### ISSUE THREAD

**Issue by xopoc14** [ableplayer/ableplayer#480]
If on the page with Ableplayer there are other scripts which use a newer version of js-cookie (in my case 3.0.0), the error occurs "jQuery.Deferred exception: Cookies.getJSON is not a function AblePlayer.prototype.getCookie". As a result Ableplayer is not loaded.

Proposed solution: remove the outdated version js-cookie from the distribution, update dependency on js-cookie to use the more actual version 3, adjust other code and documentation.

**Comment by terrill** [comment]
Fixed in 9f3806d658eab82a827b40fd07d9752213c7245d
