### ISSUE TITLE
AblePlayer play button posting back to the server when hosted in a form

### ISSUE THREAD

**Issue by Imar** [ableplayer/ableplayer#482]
Hi there,

When the AblePlayer is placed inside an HTML form element, the play icon overlay posts back to the server instead of starting the video. Here's the HTML to reproduce the issue:

```
<form method="post">
  <video id="video1" preload="auto" width="480" height="360" poster="https://ableplayer.github.io/ableplayer/media/wwa.jpg" data-able-player data-skin="2020" playsinline>
    <source type="video/mp4" src="https://ableplayer.github.io/ableplayer/media/wwa.mp4"/>
    <source type="video/webm" src="https://ableplayer.github.io/ableplayer/media/wwa.webm"/>
    <track kind="captions" src="https://ableplayer.github.io/ableplayer/media/wwa_captions_en.vtt" srclang="en" label="English captions"/>
    </video>
</form>
```
Once loaded, click the large Play icon. Instead of starting the video, the page submits to the server and simply reloads.

Is there a way to disable this behavior in the player? Should the player intercept the click event and prevent the form from being posted? 

Note: I can work around it by preventing the entire form from being submitted through script but that breaks other functionality on the same page that requires the form.

I have attached a full example with two video players: one that works and one that doesn't because of the container form.

Thanks!

[Demo.txt](https://github.com/ableplayer/ableplayer/files/7595230/Demo.txt)

**Comment by terrill** [comment]
Thanks @Imar. That's a bug. The player should intercept the click event and prevent the form from being posted.  I'll fix it soon.

**Comment by terrill** [comment]
This has been fixed in 09c90c7fb863947412ae0fe04d1b05220c771a92

**Comment by Imar** [comment]
Thanks, that looks good., Will try it out soon!

**Comment by Imar** [comment]
I was ready to update our player and take advantage of your fix and remove our work arounds, but I noticed no new release has been created since November. Will there be a new version anytime soon that will contain this fix? 

Thanks!

Imar
