### ISSUE TITLE
IE7 Compatibility

### ISSUE THREAD

**Issue by coreystaten** [ableplayer/ableplayer#49]
Player has serious issues in IE7.  What are the goals for IE7, what issues are in the way, and what is the priority for fixing them?

**Comment by terrill** [comment]
Devoted time to trying to get over IE7 hurdles today, without success.  JW Player kicks in and handles IE8 and IE9 well, but IE7 chokes on JSON (even with [json3](http://bestiejs.github.io/json3/)) and JavaScript. I'm inclined to abandon ship at this point and focus energy elsewhere, including a better ultimate fallback (see issue #103)
