### ISSUE TITLE
Blank audio transcript in version 4.4+

### ISSUE THREAD

**Issue by conorom** [ableplayer/ableplayer#490]
Discovered this when trying to upgrade Able Player in the [app I work on](https://www.fulcrum.org/concern/file_sets/6d56zz83r?locale=en), but the problem is also evident in this from your examples page:
https://ableplayer.github.io/ableplayer/demos/audio4.html

...the transcript div is completely blank. I've confirmed the issue affects both versions 4.4 and 4.4.1, but not 4.3.

Anyway, no biggie, I'll update to 4.3 for now.
aside: we're way out-of-date on 3.0 tweaked to work in Rails (with Turbolinks) so 4.3 will be a nice improvement!

Thanks for all the hard work!

**Comment by terrill** [comment]
Fixed in 51c30ed9a16e4944ae1ba767faf03bc4d8896b6f
