### ISSUE TITLE
Audio player with interactive transcript in "Lyrics Mode" broken in 4.4 and 4.4.1

### ISSUE THREAD

**Issue by mdmuzzie** [ableplayer/ableplayer#495]
With versions 4.4 and 4.4.1 of Able Player, the transcript for the audio player only shows a blank screen. You can see this in Able Player Audio Demo #4 at https://ableplayer.github.io/ableplayer/demos/audio4.html

Reverting to Able Player 4.3 fixes the issue.

<img width="1020" alt="able-player-transcript" src="https://user-images.githubusercontent.com/152531/149530195-e68f7ca2-5eb1-419b-8464-7aff890ce64f.png">

**Comment by terrill** [comment]
@mdmuzzie this has been fixed on the develop branch. It will make its way into a new release on the main branch sometime soon.
