### ISSUE TITLE
Add aria-modal to Preferences dialog

### ISSUE THREAD

**Issue by kb-smarterbalanced** [ableplayer/ableplayer#498]
Hello, we have used AblePlayer on our site: smartertoolsforteachers.org and we had an accessibility review done. This is one of the accessibility modifications that were suggested. 
**Add `aria-modal="true"`  to the element with the `role="dialog"`.**  

diff --git a/scripts/transcript.js b/scripts/transcript.js
index b06ed1e..83c454a 100644
--- a/scripts/transcript.js
+++ b/scripts/transcript.js
@@ -41,6 +41,7 @@
                this.$transcriptArea = $('<div>', {
                        'class': 'able-transcript-area',
                        'role': 'dialog',
+                       'aria-modal': 'true',
                        'aria-label': this.tt.transcriptTitle
                });

**Comment by terrill** [comment]
@kb-smarterbalanced thanks for sharing that recommendation. I agree that this needs to be added to the Preferences dialog, but **not** to the transcript or sign language pop-ups windows. These windows are not modal, i.e., users can still interact with the content behind them.  From [the definition of aria-modal in ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#aria-modal): 

> The **aria-modal** attribute is used to indicate that the presence of a "modal" element precludes usage of other content on the page. For example, when a modal dialog is displayed, it is expected that the user's interaction is limited to the contents of the dialog, until the modal dialog loses focus or is no longer displayed.

**Comment by kb-smarterbalanced** [comment]
Hi terril - thank you for the response - I will pass it on to our auditors.

**Comment by kb-smarterbalanced** [comment]
My notes:  It does seem that the developers have put thought into what they create as a modal, so I think we can accept their definition of usable as appropriate in this case. This is really a grey area and I think the able player developers have put more thought into it than the A360 report. So my answer is that I feel this was addressed and can be closed.
