### ISSUE TITLE
YouTube length problem

### ISSUE THREAD

**Issue by LinusOkidok** [ableplayer/ableplayer#501]
Seems like ableplayer can't determine the length of a youtube video. Anybody experienced similar issues?

Using [this](https://github.com/ableplayer/ableplayer/commit/54715002246b2744dec843252d8eee11f8a3343f) build
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at ableplayer.min.js:3:86675
    at K.n.ca (www.youtube.com/s/player/41de1c08/www-widgetapi.vflset/www-widgetapi.js:421:277)
    at hl (www.youtube.com/s/player/41de1c08/www-widgetapi.vflset/www-widgetapi.js:907:52)
    at pl.n.Ha (www.youtube.com/s/player/41de1c08/www-widgetapi.vflset/www-widgetapi.js:930:318)
    at www.youtube.com/s/player/41de1c08/www-widgetapi.vflset/www-widgetapi.js:895:215
    at g (www.youtube.com/s/player/41de1c08/www-widgetapi.vflset/www-widgetapi.js:504:28)

**Comment by alexarnaud** [comment]
Hello @LinusOkidok,

Are you sure the URL of your video is good? All the links on your copy/paste error point me to pages with error 404.

Could you please give us the URL of the video to check on our side?

Best regards.

**Comment by terrill** [comment]
I'm not seeing this problem in [version 4.5](https://github.com/ableplayer/ableplayer/releases/tag/v4.5), and I've tested YouTube extensively prior to this release. I'm closing this issue now. 

If you continue to observe this problem though, please post the details here and we can revisit it.
