### ISSUE TITLE
Seek bar head not aligned with seek bar

### ISSUE THREAD

**Issue by miicah** [ableplayer/ableplayer#503]
Issue: able-seekbar-head element does not align in the center of the seek bar.

You can see this on the [demo page ](https://ableplayer.github.io/ableplayer/demos/audio4.html) and I have reproduced it in my own testing as well.

It seems the value of top in the CSS needs to be adjusted.

`
.able-seekbar-head {
  top: -0.45em;
}`

I have tried -0.35em and that seems to work for the demo example, but in my own locally hosted code I needed to use -0.25em

**Comment by terrill** [comment]
@miicah that's a keen observation!  It seems to be (perhaps) less pronounced on the latest version on the [develop branch](https://github.com/ableplayer/ableplayer/tree/develop).  It also seems to be more pronounced on the audio player than on the video player (again, on the develop branch). 

As you pointed out, different values seem to work differently based on context, so I'm hesitant to make any changes without having a reliable solution that works everywhere.  

This is probably an easy fix for someone with more CSS skills than I have. I'm flagging this with the "Needs Help" label in case someone wants to tackle it.

**Comment by terrill** [comment]
@miicah I tested this with and without zoom in all major browsers on both Mac OS and WIndows, and found this value to work best across all tests using the Able Player demo pages: 

`.able-seekbar-head { top: -0.4em; }  `

That's been updated as of 7098f3ed563a5bde56f0b03cae600e412300515b
