### ISSUE TITLE
Preferences Dialogs - ARIA attributes

### ISSUE THREAD

**Issue by kb-smarterbalanced** [ableplayer/ableplayer#504]
**Suggestion from accessibiltyA360 audit:**
https://accessible360.com/
Add an `aria-modal="true"` attribute to each modal's elements with the `role="dialog"`. Additionally, remove the `aria-describedby` attributes from each modal.   

1 diff --git a/scripts/dialog.js b/scripts/dialog.js
  2 index 2e4d4db..57367a8 100644
  3 --- a/scripts/dialog.js
  4 +++ b/scripts/dialog.js
  5 @@ -41,7 +41,8 @@
  6 
  7                         modal.attr({
  8                                 'aria-labelledby': 'modalTitle-' + this.baseId,
  9 -                               'aria-describedby': 'modalDesc-' + this.baseId
 10 +                               'aria-model': 'true',
 11 +                               'role': 'dialog',
 12                         });
 13                         modal.prepend(titleH1);
 14                         modal.prepend(closeButton);

**Comment by terrill** [comment]
Fixed in 61b678f801c29eb795cf6b2c8d92c44a73b42ba5
