### ISSUE TITLE
Add H1 heading to transcript modal

### ISSUE THREAD

**Issue by kb-smarterbalanced** [ableplayer/ableplayer#507]
From accessibility 360 audit - https://accessible360.com/

Give this modal dialog an `<h1>` heading. If this does not conform to styling, instead add this heading as a screen reader-only heading. For example, the screen reader only heading could read "Video Transcript" or similar.

**Comment by terrill** [comment]
@kb-smarterbalanced is this a different issue than #508?  Unless I'm misunderstanding one or the other, I think both issues are concerned with the heading of the transcript, yes?  I'm going to close this issue, but welcome discussion in the other issue.
