### ISSUE TITLE
Disable Suggested Videos on YouTube & Hide Watermark

### ISSUE THREAD

**Issue by alikhan27** [ableplayer/ableplayer#510]
Hi,
I am trying two things in Youtube embed videos which i couldn't find in the documentation.

1. Disable Suggested Videos
2. Hiding the watermark of Youtube.

Is there a way to do? and any suggestion pls.

Thanks

**Comment by terrill** [comment]
Unfortunately neither of these is possible.  With the [YouTube IFrame Player API](https://developers.google.com/youtube/player_parameters?playerVersion=HTML5), these are the relevant parameters: 

- **controls** - set to "0" to hide YouTube's player controls, or "1" to show them.  We're hiding them and replacing them with Able Player controls. 
- **modestbranding** - set to "1" to hide the YouTube logo from the player controller. This works if controls="1" (i.e., the logo can be hidden from the default YouTube player controller). However, if controls="0" YouTube adds a logo to the bottom right corner of the video and there doesn't seem to be any way to prevent that. 
- **rel** - It used to be possible to disable related videos with rel="0". However, as explained in the API documentation, that changed in 2018 so rel="0" limits related videos to videos that come from the same channel as the video that was just played. The only other value for this parameter is "1", which shows related videos without limitations.
