### ISSUE TITLE
Full-screen video does not work with Vimeo

### ISSUE THREAD

**Issue by camcgee** [ableplayer/ableplayer#511]
When using Ableplayer with Vimeo, the full-screen button makes the player full screen, but the video itself does not re-scale and stays the same size as whatever width is initially set for the video. 
The behavior can be seen in the Vimeo demo pages, e.g.:  https://ableplayer.github.io/ableplayer/demos/vimeo1.html

**Comment by terrill** [comment]
@camcgee this has been fixed in the [develop](https://github.com/ableplayer/ableplayer/tree/develop) branch, and will be fixed in the main branch soon.
