### ISSUE TITLE
data-vimeo-id cannot contain URL query parameters

### ISSUE THREAD

**Issue by theMusician** [ableplayer/ableplayer#515]
In working with Vimeo, one can create private videos that can be shared via URL. These private URLs always seem to contain query parameters,

Something like https://player.vimeo.com/video/691499558?h=3bd3e036bb where ?h=alphanumeric string is the query parameter. If that parameter is included with the video id in the the data-vimeo-id parameter, Able Player doesn't seem to load the video. 

Is there something that strips the query parameter from vimeo ids in the Able Player source? I don't have many of these types of videos but it would be nice if they could be handled via AblePlayer.

**Comment by terrill** [comment]
@theMusician thanks for the heads-up.  Vimeo ID is extracted from the URL in vimeo.js > getVimeoId(), which probably isn't properly accounting for the possibility of parameters on the URL. It should be an easy fix.

**Comment by terrill** [comment]
Update: Able Player can play the video now, but the caption toggle doesn't seem to work. Investigating...

**Comment by terrill** [comment]
OK, caption bug fixed in b3ef0af0c0f265747ccf86b3f6aa5ed8e390c99f
