### ISSUE TITLE
Vimeo videos do not resize when the user goes into fullscreen mode.

### ISSUE THREAD

**Issue by pope7** [ableplayer/ableplayer#517]
First off, amazing work.

Vimeo videos don't seem to be resizing when you click to go fullscreen. The iframe stays its original size and hangs out in the corner. This is a HUGE issue to me, unfortunately, and it's limiting my ability to use this tool for internal documentation. Thanks for any help!

**Comment by terrill** [comment]
@pope7 have you tried with the latest version on the [develop branch](https://github.com/ableplayer/ableplayer/tree/develop)?  I think this issue has been fixed.

**Comment by pope7** [comment]
100% fixed in dev branch, thank you.
