### ISSUE TITLE
Play/Pause Bug in Playlists -Unable to Resume Video/Audio

### ISSUE THREAD

**Issue by kevdevlu** [ableplayer/ableplayer#519]
https://ableplayer.github.io/ableplayer/demos/video15.html

1. Click **Play** on the **body of the video** (not in the controls on the bottom pane)
2. Click **Pause** by clicking on the **body of the video** (not in the controls on the bottom pane)
3. There is no way for the video to resume play unless you reload the page or adjust to a different part of the video

There doesn't seem to be any bug like this when individual videos/audios are played. Only in playlists.

Any solution would be deeply appreciated.
- kevdev

**Comment by terrill** [comment]
Fixed in cad1ef3f85609a537f615f2eb955d1abb7f13672
