### ISSUE TITLE
Error on YouTube video without CC

### ISSUE THREAD

**Issue by mshubat** [ableplayer/ableplayer#520]
When a YT video is missing closed captions there is a TypeError in the browser
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at ableplayer.js:5988:29
    at n.fa (www-widgetapi.js:461:277)
```
![image](https://user-images.githubusercontent.com/10766136/171887186-f50bebae-9693-4933-9eee-230554547b63.png)

This error can be reproduced with any video without captions. Here are a couple:
- https://www.youtube.com/watch?v=oZVABbuJSkM
- https://www.youtube.com/watch?v=sjkrrmBnpGE

**Comment by terrill** [comment]
Closed with 6e3899d0f8841d0e4f19738dff2219dc8dc07935
