### ISSUE TITLE
Tooltips are not dismissible 

### ISSUE THREAD

**Issue by mshubat** [ableplayer/ableplayer#522]
Tooltip content for the following buttons are not dismissible:
-Play
-Restart
-Rewind
-Forward
-Hide captions
-Faster
-Slower
-Preferences
-Volume

Content on hover or focus needs to be dismissible without moving the pointer

See https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus

>Dismissible
>A [mechanism](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus#dfn-mechanism) is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an 
 [input error](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus#dfn-input-error) or does not obscure or replace other content;

![image](https://user-images.githubusercontent.com/10766136/172427505-b8a8a0fe-8c95-4bb9-984b-ea69aadfeaea.png)

**Comment by mshubat** [comment]
The PR Above includes the changes to make the tooltips dismissible via the escape key.

**Comment by terrill** [comment]
Closed with 6e3899d0f8841d0e4f19738dff2219dc8dc07935
