### ISSUE TITLE
Tooltips are not Hoverable

### ISSUE THREAD

**Issue by mshubat** [ableplayer/ableplayer#523]
Additional content that becomes available on hover does not allow the user to move the pointer over that same additional content without the additional content disappearing.

Element: Tooltip content for the following buttons
-Play
-Restart
-Rewind
-Forward
-Hide captions
-Faster
-Slower
-Preferences
-Volume

See https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus

> If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;

![tooltip-dissapears](https://user-images.githubusercontent.com/10766136/172639951-5986eb18-acd3-4800-9b95-abab319f07e2.gif)

**Comment by terrill** [comment]
Closed with 6e3899d0f8841d0e4f19738dff2219dc8dc07935
