### ISSUE TITLE
Pressed state of CC button not present with Single Caption

### ISSUE THREAD

**Issue by mshubat** [ableplayer/ableplayer#528]
The pressed state of the Captions button is not conveyed to screen readers when there is only a single caption.

Fix this issue by using the aria-pressed attribute on the toggle button to convey its pressed or unpressed state.

![image](https://user-images.githubusercontent.com/10766136/174369916-5b5c2c7a-49e5-4839-8623-a7d26d705465.png)

**Comment by terrill** [comment]
Closed with 6e3899d0f8841d0e4f19738dff2219dc8dc07935
