### ISSUE TITLE
Blank audio transcript

### ISSUE THREAD

**Issue by njaffe3** [ableplayer/ableplayer#531]
In the example, [Able Player Audio Demo #4: Audio player with interactive transcript in "Lyrics Mode,"](https://ableplayer.github.io/ableplayer/demos/audio4.html) the interactive transcript isn't showing up. The same thing is happening when I've tested this on a dev site. The transcript button shows up along with the popup, but there is no text inside. The video transcript appears to be working correctly.
<img width="1028" alt="Screen Shot 2022-06-29 at 11 37 24 AM" src="https://user-images.githubusercontent.com/10766449/176511711-df552cec-b0bf-4095-a718-0b0c2ea5e0d0.png">

**Comment by njaffe3** [comment]
Seems to be the same issue as #490

**Comment by terrill** [comment]
@njaffe3 as noted in the comments in #490, this has been fixed as of https://github.com/ableplayer/ableplayer/commit/51c30ed9a16e4944ae1ba767faf03bc4d8896b6f - still on the **develop** branch but it will be merged soon into a new release.
