### ISSUE TITLE
Lyrics Mode text does not show

### ISSUE THREAD

**Issue by gaslamp-dennis** [ableplayer/ableplayer#543]
I tried implementing the lyrics mode and couldn't get it to work. I found an example on the demo page but that is not working either. The popup box is just empty.

An issue with the current version of Able Player?
https://ableplayer.github.io/ableplayer/demos/audio4.html

<img width="984" alt="Screen Shot 2022-07-15 at 2 43 52 PM" src="https://user-images.githubusercontent.com/91696437/179315018-6ab0993a-aa9e-499f-aab5-2b4a50838a01.png">

**Comment by terrill** [comment]
@gaslamp-dennis this has been fixed on the [Develop branch](https://github.com/ableplayer/ableplayer/tree/develop).  I'll be merging that with the main branch and publishing a new release soon.

**Comment by gaslamp-dennis** [comment]
Thanks, @terrill!

**Comment by kelvinq** [comment]
Should we keep this open so that other developers may find this useful and switch to the develop branch?

**Comment by terrill** [comment]
@kelvinq no, I should hurry up and merge develop with main. I hate to keep saying "soon" and failing to deliver, but... 
Soon!
