### ISSUE TITLE
Transcript button not showing

### ISSUE THREAD

**Issue by NayanKhedkar** [ableplayer/ableplayer#563]
The transcript button not showing when using the transcript as an external div

**Comment by NayanKhedkar** [comment]
PR: https://github.com/ableplayer/ableplayer/pull/564

**Comment by NayanKhedkar** [comment]
@terrill Could you please review the PR: https://github.com/ableplayer/ableplayer/pull/564 ?

**Comment by candidexmedia** [comment]
@NayanKhedkar If I'm not mistaken, you have to make PRs in the "dev" branch. Looks like you've made it in the main branch.

**Comment by NayanKhedkar** [comment]
Thanks @candidexmedia , will check and updated the fixes to "dev"

**Comment by jeanem** [comment]
Hello @NayanKhedkar.  This appears to be working as expected. In the [documentation there is this note](https://ableplayer.github.io/ableplayer/#transcript): 

> .. a toggle button is added to the controller only if the transcript is a “popup” type; there is no toggle button for either the “external” or “manual” transcript types.

Its based on the assumption that if either of these options are chosen, a persistent display of the transcript is desired. 

If you'd like this functionality added, please feel free to open a feature request with use case details.

Thank-you.
