### ISSUE TITLE
Bug - Multiple players pref save.

### ISSUE THREAD

**Issue by harlet** [ableplayer/ableplayer#568]
<img width="1334" alt="external5 html 2023-02-16 15-26-52" src="https://user-images.githubusercontent.com/5509330/219377248-89ad4630-b910-43df-b06e-67284047cc96.png">

The error occurs on this [line](https://github.com/ableplayer/ableplayer/blob/main/scripts/preference.js#L1100) because the functions does not exist or have been renamed. I think that it should be `loadCurrentPreferences()` instead.

**Comment by terrill** [comment]
Closing this, as it's a duplicate of #571 .
