### ISSUE TITLE
Want to open another layer instead of modal for settings

### ISSUE THREAD

**Issue by banerjeesoumya1** [ableplayer/ableplayer#572]
Hello All,

I am trying to customize the able player setting popup menu that is opening up. I want to move the speed under the settings, with fonts size instead of opening under modal want to show multiple options for font size such as 
Smallest | Smaller | Small | Normal | Large | Larger | Largest 

My inspiration is how YouTube displays their settings. YouTube Eg. settings >  playback speed > we click on the playback speed another layer showing the playback speed appears.

Would appreciate if anyone can help.

**Comment by terrill** [comment]
@banerjeesoumya1 you essentially are wanting to rebuild the interface, which is no small endeavor.  For starters, I suggest searching all scripts/*.js files for **this.skin**.  We currently have two slightly different skins "legacy" and "2020", and this will give you a sense for where the differences are defined, and the impact they have.  

Also, note that if you introduce new words into the interface (e.g., Smallest | Smaller | Small | Normal | Large | Larger | Largest) those will need to be added to the translation files and translated into each of the supported languages, unless your intent is for your player to be used only for your own purposes, and only in one language.

**Comment by banerjeesoumya1** [comment]
Thanks @terrill will try this
