### ISSUE TITLE
Add preferences for setting caption color, size, and background opacity.

### ISSUE THREAD

**Issue by kensgists** [ableplayer/ableplayer#65]
Not asking for something as comprehensive as what YouTube offers, but I think it would be a good (expected?) accommodation to allow a user to select between white, yellow, and bright green for colors, small, normal, and large for size, and between no background (0.0), 25%, 50%, 75%, and solid/opaque background.

**Comment by terrill** [comment]
YouTube only offers eight color choices, which seems reasonable: 
 white, yellow, green, cyan, blue, magenta, red, black

**Comment by terrill** [comment]
Added in a871a787400ac1faed8263874f42649a6f67bb45
