### ISSUE TITLE
Youtube is sometimes failing to load

### ISSUE THREAD

**Issue by coreystaten** [ableplayer/ableplayer#73]
Youtube player initialization is sometimes failing, especially (perhaps?) in Firefox.  Suspect this is an issue related to loading and running the youtube iframe API script?

**Comment by terrill** [comment]
Lots more work with YouTube over the past few days, and still no load failures in either Firefox or Chrome. I did observe that YouTube's HTML5 player loads a bit slower in Firefox than their AS3 (Flash) player does, but it isn't failing. Maybe this has been resolved in either a Firefox upgrade or a YouTube upgrade. Satisfied that all is well, I'm closing this issue.
