### ISSUE TITLE
Saving preferences only affects current player on pages with multiple players

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#86]
1. The visible focus indicators don't work. 
2. Each player has its own Preferences dialog, and when data is saved from one that doesn't automatically effect the other (seeing a change in the other dialog requires a page refresh)  

This is observable in Test8 and Test9

**Comment by terrill** [comment]
Visible focus indicator is no longer a problem. Therefore, changing the name of this issue to reflect the one remaining problem (Preferences). Relevant functions are in preference.js. When user saves their Preferences, this.savePrefsFromForm() is called, which in turn calls this.updatePrefs(). These would need to be executed in *all* players on the page, not just the current one.

**Comment by inwebitrust** [comment]
Hello,

Has anyone be able to avoid this problem ?

When multiple players on same page, saving preferences won't work.

Thanks

**Comment by terrill** [comment]
This is now fixed in 750cd0d96042be27f2f12252ed5069a32febf0b8
