### ISSUE TITLE
Captions/transcript break on `</v>`

### ISSUE THREAD

**Issue by nwtn** [ableplayer/ableplayer#90]
According to [the spec](http://dev.w3.org/html5/webvtt/) and the [Live WebVTT Validator](https://quuz.org/webvtt/), `<v>` tags can be closed with `</v>`. In my experience, doing this breaks the captions and transcript in AblePlayer.

E.g:

````
00:02:06.060 --> 00:02:09.619
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus

00:02:09.619 --> 00:02:12.800
<v Speaker A>Consectetur adipiscing elit</v>
<v Speaker B> ―Donec a diam lectus</v>
````

In the example above, I'm not getting any captions/transcript beyond 00:02:09.619.

**Comment by terrill** [comment]
This has been confirmed, it's fixed.
