### ISSUE TITLE
Changing directory layout causes the player not to load

### ISSUE THREAD

**Issue by pvagner** [ableplayer/ableplayer#91]
Steps to reproduce
- Clone / download the able-player source tree
- Move the file tests/test1.html to the project parent directory (the same folder where the file Readme.md can be found).
- Edit the file test1.html so reference to the tests.css file gets completelly removed and also change all relative paths starting with double full stops to start with single full stop instead.
- Open the resulting test1.html in a browser of your choice

Actual results
The player won't load with no errors printed to the javascript console.

Expected results
Player should load as all the relative paths are correct and are pointing to the proper resources.

**Comment by terrill** [comment]
An even better fix was implemented in 32e04979fc3fd4bdb9d11a782f5b6c40f063efcc
