### ISSUE TITLE
Support alternate caption & chapters when length of audio-described video does not match original

### ISSUE THREAD

**Issue by joedolson** [ableplayer/ableplayer#93]
If an audio-described video is a different lengh than the original source, the timepoints specified in caption and chapter data won't align with the video anymore. Toggling to an alternate version of those files would allow use of those features predictably.

**Comment by terrill** [comment]
Elevating the priority of this issue, now that 3PlayMedia and AutomaticSync are making it easy to produce extended audio description.

**Comment by terrill** [comment]
Escalating this to Top priority. Here's the implementation logic: 

- If any `<track>` element has a `data-desc` attribute, use that track only for the described version of the video, and use all others for the non-described version.  
- If no `<track>` elements have a `data-desc` attribute, and the described and non-described versions of the video are **the same duration**, use all tracks for both versions. 
- If no `<track>` elements have a `data-desc` attribute, and the described and non-described versions of the video are **different durations**, use all tracks for the non-described version only. They will be out-of-sync if used for the described version.

**Comment by terrill** [comment]
This has been addressed in the [version 4.5](https://github.com/ableplayer/ableplayer/releases/tag/v4.5).
