### ISSUE TITLE
Drupal Module

### ISSUE THREAD

**Issue by mgifford** [ableplayer/ableplayer#95]
Would be great if there were a Drupal module to help leverage this code.

**Comment by mgifford** [comment]
Discussion of this on GDO - https://groups.drupal.org/node/464908

**Comment by afemath** [comment]
I have started woking on a module for this -> https://www.drupal.org/sandbox/afemath/2475577

It is currently just a sandbox module and is in development.

**Comment by theMusician** [comment]
Work is in progress to integrate AblePlayer with Drupal's media project WYSIWYG. 

[Able Player YouTube](https://bitbucket.org/wwuweb/ableplayer_youtube) is not yet a sandbox project but is getting close.
[Able Player library](https://www.drupal.org/sandbox/npacker/2508441) is a sandbox project and leverages the libraries module to provide integration with Able Player.

**Comment by npacker** [comment]
I have a couple sandbox projects up that handle Able Player integration.

**[Able Player](https://www.drupal.org/sandbox/npacker/2508441)** integrates Able Player with the **[Libraries API](https://www.drupal.org/project/libraries)** and the [Modernizr Test API](https://www.drupal.org/node/2332277). At present, this project is intended for use by other developers who want to use the Able Player code; it does not provide any formatters or displays of its own. It guides proper installation of the Able Player code and dependencies.

**[Able Player: YouTube](https://www.drupal.org/sandbox/npacker/2527774)** enables Able Player as a file display for YouTube videos added via the [Media: YouTube](https://www.drupal.org/project/media_youtube) module. It therefore depends on [Media](https://www.drupal.org/project/media).

Being fairly new to Drupal module development, I'm not sure if it makes most sense to have a single Able Player module that handles YouTube and everything else, or if they should stay separate. I welcome input from other developers looking to use Able Player with Drupal as to what direction to take next.

**Comment by mgifford** [comment]
Nice to see progress on this! @npacker did you work on @theMusician code or start from scratch?

What do we need to do to see a stable release?

**Comment by npacker** [comment]
@mgifford I work with @theMusician, the linked projects are the same. I'm working with him to get the sandbox projects promoted to official modules.

Along with that, I've filed an issue with the Drupal sandbox @afemath started above, hoping that we can somehow combine or integrate our respective projects. Things have been quiet there for  the past couple months, so I intend to forge ahead either way.

Other than that, feature requests and development contributions are welcome. Issues can be filed on the sandbox projects. Probably wouldn't hurt to get more attention on this as well; if you know of other interested parties, direct them here or to the GDO discussion.

**Comment by mgifford** [comment]
Brilliant.. Looking forward to taking a look at it when it's more ready.

**Comment by npacker** [comment]
@mgifford I've opened a ticket to get the Able Player sandbox project that I have been developing promoted to a full module. 

**[Project Application](https://www.drupal.org/node/2545710)**
**[Able Player Project Page](https://www.drupal.org/sandbox/npacker/2508441)**

Some things to note:
* I have combined the Able Player and Able Player YouTube modules; YouTube support is now handled via an included sub-module that requires Media: YouTube.
* The separate and unrelated "Ableplayer" sandbox started by @afemath appears to be no longer under active development. As such I've moved forward with a full implementation. At this point I believe my sandbox is more complete, particularly with multilingual transcript support.

Please, consider testing the sandbox project, linked above. The more feedback we can get, the faster it will become a full module. [How to review Full Project applications](https://www.drupal.org/node/894256)

**Comment by mgifford** [comment]
I'll keep an eye on it and try to test it out later today.

**Comment by JLiliam** [comment]
Hi
I would know about the Able Palyer Module for Drupal. Is it available?  I'm a new digital humanist and I want to use it in a project.

Thank you.

**Comment by terrill** [comment]
@JLiliam It hasn't been super actively maintained, but you can find it on the the [Able Player project page](https://www.drupal.org/project/ableplayer) at drupal.org.

**Comment by JLiliam** [comment]
@terrill
Thank you. Can I use it in Drupal 8? I'm sorry if this seems a so basic question, but I'm just learning to read the Drupal modules info. 

It would be great that this module gets active a gain!

**Comment by npacker** [comment]
@JLiliam The module is for Drupal 7 and Ableplayer version 2. I have not tested whether or not it is compatible with version 3.

**Comment by JLiliam** [comment]
@terrill  and @npacker Thank you guys!!!

**Comment by mgifford** [comment]
Probably good to put something in the Drupal project description https://www.drupal.org/project/ableplayer and also in the issue queue https://www.drupal.org/project/issues/ableplayer to let folks know where the development is being done. 

It's always possible to hire folks to upgrade these modules if you've got the budget to do so. Would be nice to have a stable release for D8. 

Also, it's a good best practice to put out releases on Drupal.org simply because then sites can take care of the Drupal Security model for updates.

**Comment by JLiliam** [comment]
Hi!
I installed the Able Player module and its dependences, but It doesn't work. Able Player is not listed in the Status Report of my site. Can you help me, please?

**Comment by terrill** [comment]
I'm closing this issue here. Please submit any questions related to the [Able Player Drupal Module](https://www.drupal.org/project/ableplayer) to the [Able Player Issues queue on Drupal.org](https://www.drupal.org/project/issues/ableplayer)
